/**
 * Omniquest: Realm of Shadows - Comprehensive Master Item Catalog Data
 * Fully expanded item definitions with complete combat properties, stat matrices, and lore texts.
 */

export interface DetailedCatalogItem {
  id: string;
  name: string;
  slot: 'MainHand' | 'OffHand' | 'TwoHand' | 'Helmet' | 'ChestArmor' | 'Gloves' | 'Boots' | 'Ring' | 'Amulet' | 'Relic';
  rarity: 'Common' | 'Uncommon' | 'Rare' | 'Epic' | 'Legendary' | 'Mythic' | 'Artifact';
  itemLevel: number;
  requiredLevel: number;
  attackPower: number;
  spellPower: number;
  armorRating: number;
  maxHealthBonus: number;
  maxEnergyBonus: number;
  critChancePct: number;
  critMultiplierBonus: number;
  movementSpeedBonusPct: number;
  lifeStealPct: number;
  fireResistancePct: number;
  frostResistancePct: number;
  shadowResistancePct: number;
  holyResistancePct: number;
  lightningResistancePct: number;
  poisonResistancePct: number;
  specialAffixDescription: string;
  flavorLoreText: string;
  baseGoldValue: number;
  durabilityMax: number;
}

export const COMPREHENSIVE_ITEM_CATALOG_DATA: DetailedCatalogItem[] = [
  {
    id: 'item_cat_0001',
    name: 'Rusty Iron Gladius',
    slot: 'MainHand',
    rarity: 'Common',
    itemLevel: 1,
    requiredLevel: 1,
    attackPower: 12,
    spellPower: 0,
    armorRating: 0,
    maxHealthBonus: 5,
    maxEnergyBonus: 0,
    critChancePct: 5.0,
    critMultiplierBonus: 1.5,
    movementSpeedBonusPct: 0.0,
    lifeStealPct: 0.0,
    fireResistancePct: 0.0,
    frostResistancePct: 0.0,
    shadowResistancePct: 0.0,
    holyResistancePct: 0.0,
    lightningResistancePct: 0.0,
    poisonResistancePct: 0.0,
    specialAffixDescription: 'Standard issue blade for arena initiates.',
    flavorLoreText: 'Dug up from the ruined training grounds outside Eldoria.',
    baseGoldValue: 15,
    durabilityMax: 60
  },
  {
    id: 'item_cat_0002',
    name: 'Tempered Steel Shortsword',
    slot: 'MainHand',
    rarity: 'Common',
    itemLevel: 1,
    requiredLevel: 1,
    attackPower: 16,
    spellPower: 0,
    armorRating: 0,
    maxHealthBonus: 8,
    maxEnergyBonus: 0,
    critChancePct: 6.0,
    critMultiplierBonus: 1.5,
    movementSpeedBonusPct: 0.0,
    lifeStealPct: 0.0,
    fireResistancePct: 0.0,
    frostResistancePct: 0.0,
    shadowResistancePct: 0.0,
    holyResistancePct: 0.0,
    lightningResistancePct: 0.0,
    poisonResistancePct: 0.0,
    specialAffixDescription: 'Well-balanced edge allowing quick recovery between strikes.',
    flavorLoreText: 'Stamped with the crest of the Redshore blacksmith guild.',
    baseGoldValue: 25,
    durabilityMax: 80
  },
  {
    id: 'item_cat_0003',
    name: 'Honed Obsidian Dagger',
    slot: 'MainHand',
    rarity: 'Uncommon',
    itemLevel: 1,
    requiredLevel: 1,
    attackPower: 14,
    spellPower: 0,
    armorRating: 0,
    maxHealthBonus: 0,
    maxEnergyBonus: 10,
    critChancePct: 12.0,
    critMultiplierBonus: 1.8,
    movementSpeedBonusPct: 4.0,
    lifeStealPct: 0.0,
    fireResistancePct: 0.0,
    frostResistancePct: 0.0,
    shadowResistancePct: 5.0,
    holyResistancePct: 0.0,
    lightningResistancePct: 0.0,
    poisonResistancePct: 0.0,
    specialAffixDescription: 'Critical strikes deal 20% additional puncture damage.',
    flavorLoreText: 'Carved from volcanic obsidian that absorbs ambient light.',
    baseGoldValue: 45,
    durabilityMax: 50
  },
  {
    id: 'item_cat_0004',
    name: 'Oak Quarterstaff of Arcana',
    slot: 'TwoHand',
    rarity: 'Common',
    itemLevel: 1,
    requiredLevel: 1,
    attackPower: 8,
    spellPower: 22,
    armorRating: 2,
    maxHealthBonus: 12,
    maxEnergyBonus: 25,
    critChancePct: 4.0,
    critMultiplierBonus: 1.4,
    movementSpeedBonusPct: 0.0,
    lifeStealPct: 0.0,
    fireResistancePct: 0.0,
    frostResistancePct: 0.0,
    shadowResistancePct: 0.0,
    holyResistancePct: 0.0,
    lightningResistancePct: 0.0,
    poisonResistancePct: 0.0,
    specialAffixDescription: 'Increases mana regeneration by 2 points per second.',
    flavorLoreText: 'Carved from ancient grove timber, resonant with magic.',
    baseGoldValue: 30,
    durabilityMax: 70
  },
  {
    id: 'item_cat_0005',
    name: 'Spiked Morningstar of Ruin',
    slot: 'MainHand',
    rarity: 'Uncommon',
    itemLevel: 1,
    requiredLevel: 1,
    attackPower: 22,
    spellPower: 0,
    armorRating: 4,
    maxHealthBonus: 15,
    maxEnergyBonus: 0,
    critChancePct: 4.0,
    critMultiplierBonus: 1.6,
    movementSpeedBonusPct: -2.0,
    lifeStealPct: 0.0,
    fireResistancePct: 0.0,
    frostResistancePct: 0.0,
    shadowResistancePct: 0.0,
    holyResistancePct: 0.0,
    lightningResistancePct: 0.0,
    poisonResistancePct: 0.0,
    specialAffixDescription: 'Bypasses 15% of heavy monster armor.',
    flavorLoreText: 'A brutal iron flange designed to crack skeletal ribs.',
    baseGoldValue: 50,
    durabilityMax: 90
  },
  {
    id: 'item_cat_0006',
    name: 'Frostbound Crystal Wand',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 2,
    requiredLevel: 1,
    attackPower: 6,
    spellPower: 35,
    armorRating: 0,
    maxHealthBonus: 10,
    maxEnergyBonus: 35,
    critChancePct: 8.0,
    critMultiplierBonus: 1.6,
    movementSpeedBonusPct: 0.0,
    lifeStealPct: 0.0,
    fireResistancePct: 0.0,
    frostResistancePct: 20.0,
    shadowResistancePct: 0.0,
    holyResistancePct: 0.0,
    lightningResistancePct: 0.0,
    poisonResistancePct: 0.0,
    specialAffixDescription: 'Frost spells have a 15% chance to freeze normal enemies.',
    flavorLoreText: 'Its tip contains an unmelting sapphire shard from the northern crags.',
    baseGoldValue: 95,
    durabilityMax: 65
  },
  {
    id: 'item_cat_0007',
    name: 'Flametongue Scimitar',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 2,
    requiredLevel: 2,
    attackPower: 32,
    spellPower: 15,
    armorRating: 0,
    maxHealthBonus: 20,
    maxEnergyBonus: 15,
    critChancePct: 10.0,
    critMultiplierBonus: 1.7,
    movementSpeedBonusPct: 5.0,
    lifeStealPct: 0.0,
    fireResistancePct: 25.0,
    frostResistancePct: -10.0,
    shadowResistancePct: 0.0,
    holyResistancePct: 0.0,
    lightningResistancePct: 0.0,
    poisonResistancePct: 0.0,
    specialAffixDescription: 'Striking an enemy ignites them for 12 fire damage over 4s.',
    flavorLoreText: 'The curved steel glow orange in darkened dungeon corridors.',
    baseGoldValue: 120,
    durabilityMax: 85
  },
  {
    id: 'item_cat_0008',
    name: 'Thunderclap Greatmaul',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 2,
    requiredLevel: 2,
    attackPower: 55,
    spellPower: 0,
    armorRating: 10,
    maxHealthBonus: 40,
    maxEnergyBonus: 0,
    critChancePct: 6.0,
    critMultiplierBonus: 2.0,
    movementSpeedBonusPct: -4.0,
    lifeStealPct: 0.0,
    fireResistancePct: 0.0,
    frostResistancePct: 0.0,
    shadowResistancePct: 0.0,
    holyResistancePct: 0.0,
    lightningResistancePct: 25.0,
    poisonResistancePct: 0.0,
    specialAffixDescription: 'Ground slam attacks release concussive electric shockwaves.',
    flavorLoreText: 'Forged atop Mount Thunderpeak during a lightning storm.',
    baseGoldValue: 140,
    durabilityMax: 110
  },
  {
    id: 'item_cat_0009',
    name: 'Viper Fang Stiletto',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 2,
    requiredLevel: 2,
    attackPower: 28,
    spellPower: 0,
    armorRating: 0,
    maxHealthBonus: 10,
    maxEnergyBonus: 20,
    critChancePct: 16.0,
    critMultiplierBonus: 1.9,
    movementSpeedBonusPct: 8.0,
    lifeStealPct: 5.0,
    fireResistancePct: 0.0,
    frostResistancePct: 0.0,
    shadowResistancePct: 15.0,
    holyResistancePct: 0.0,
    lightningResistancePct: 0.0,
    poisonResistancePct: 30.0,
    specialAffixDescription: 'Attacks inflict neurotoxin slowing enemy attack speed by 25%.',
    flavorLoreText: 'Dipped in the venom sacs of swamp hydras.',
    baseGoldValue: 135,
    durabilityMax: 70
  },
  {
    id: 'item_cat_0010',
    name: 'Staff of the Glacial Archon',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 3,
    requiredLevel: 2,
    attackPower: 15,
    spellPower: 75,
    armorRating: 15,
    maxHealthBonus: 45,
    maxEnergyBonus: 80,
    critChancePct: 10.0,
    critMultiplierBonus: 1.8,
    movementSpeedBonusPct: 0.0,
    lifeStealPct: 0.0,
    fireResistancePct: 0.0,
    frostResistancePct: 45.0,
    shadowResistancePct: 15.0,
    holyResistancePct: 0.0,
    lightningResistancePct: 0.0,
    poisonResistancePct: 0.0,
    specialAffixDescription: 'Summons a swirling ice barrier absorbing 150 damage.',
    flavorLoreText: 'Ancient staff carried by the high wizards of the Glacial Citadel.',
    baseGoldValue: 280,
    durabilityMax: 100
  },
  {
    id: 'item_cat_0011',
    name: 'Cuirass of the Iron Titan',
    slot: 'ChestArmor',
    rarity: 'Epic',
    itemLevel: 3,
    requiredLevel: 2,
    attackPower: 15,
    spellPower: 0,
    armorRating: 95,
    maxHealthBonus: 140,
    maxEnergyBonus: 15,
    critChancePct: 0.0,
    critMultiplierBonus: 1.0,
    movementSpeedBonusPct: -3.0,
    lifeStealPct: 0.0,
    fireResistancePct: 20.0,
    frostResistancePct: 20.0,
    shadowResistancePct: 20.0,
    holyResistancePct: 20.0,
    lightningResistancePct: 20.0,
    poisonResistancePct: 20.0,
    specialAffixDescription: 'Reduces all incoming physical damage by 18%.',
    flavorLoreText: 'Tempered in the deepest magma vaults of the mountain.',
    baseGoldValue: 320,
    durabilityMax: 150
  },
  {
    id: 'item_cat_0012',
    name: 'Robes of the Solar Phoenix',
    slot: 'ChestArmor',
    rarity: 'Epic',
    itemLevel: 3,
    requiredLevel: 2,
    attackPower: 0,
    spellPower: 80,
    armorRating: 30,
    maxHealthBonus: 60,
    maxEnergyBonus: 110,
    critChancePct: 12.0,
    critMultiplierBonus: 1.8,
    movementSpeedBonusPct: 6.0,
    lifeStealPct: 0.0,
    fireResistancePct: 60.0,
    frostResistancePct: -15.0,
    shadowResistancePct: 10.0,
    holyResistancePct: 25.0,
    lightningResistancePct: 0.0,
    poisonResistancePct: 0.0,
    specialAffixDescription: 'Fire spells have 25% chance to trigger an instant free cast.',
    flavorLoreText: 'Woven from feathers molted by the legendary Solar Phoenix.',
    baseGoldValue: 340,
    durabilityMax: 90
  },
  {
    id: 'item_cat_0013',
    name: '👑 Worldbreaker Greatsword of the Overlord',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 5,
    requiredLevel: 3,
    attackPower: 160,
    spellPower: 45,
    armorRating: 40,
    maxHealthBonus: 200,
    maxEnergyBonus: 50,
    critChancePct: 25.0,
    critMultiplierBonus: 2.5,
    movementSpeedBonusPct: 15.0,
    lifeStealPct: 12.0,
    fireResistancePct: 40.0,
    frostResistancePct: 40.0,
    shadowResistancePct: 60.0,
    holyResistancePct: 20.0,
    lightningResistancePct: 30.0,
    poisonResistancePct: 40.0,
    specialAffixDescription: 'Critical strikes trigger a cataclysmic meteor storm hitting all screen foes.',
    flavorLoreText: 'The ancient dread blade that ruled the Abyssal Throne for ten thousand cycles.',
    baseGoldValue: 1500,
    durabilityMax: 300
  },
  {
    id: 'item_cat_0014',
    name: '👑 Heart of the Eternal Sun',
    slot: 'Relic',
    rarity: 'Artifact',
    itemLevel: 5,
    requiredLevel: 3,
    attackPower: 50,
    spellPower: 70,
    armorRating: 35,
    maxHealthBonus: 250,
    maxEnergyBonus: 150,
    critChancePct: 18.0,
    critMultiplierBonus: 2.2,
    movementSpeedBonusPct: 20.0,
    lifeStealPct: 15.0,
    fireResistancePct: 50.0,
    frostResistancePct: 50.0,
    shadowResistancePct: 50.0,
    holyResistancePct: 50.0,
    lightningResistancePct: 50.0,
    poisonResistancePct: 50.0,
    specialAffixDescription: 'Grants invulnerability when dropping below 20% health for 4.0s.',
    flavorLoreText: 'A living spark of the primordial creation star, pulsing with pure vitality.',
    baseGoldValue: 2500,
    durabilityMax: 500
  }
];

export class ComprehensiveItemCatalogData {
  public static getCatalog(): DetailedCatalogItem[] {
    return COMPREHENSIVE_ITEM_CATALOG_DATA;
  }
}
