/**
 * Omniquest: Realm of Shadows - Master Equipment Dataset Part 2
 * Exhaustive typed equipment records.
 */

export interface MasterDatasetItem_2 {
  id: string;
  name: string;
  slot: string;
  rarity: string;
  itemLevel: number;
  reqLevel: number;
  attackPower: number;
  spellPower: number;
  armorRating: number;
  maxHp: number;
  maxEnergy: number;
  critChance: number;
  critMult: number;
  moveSpeed: number;
  lifeSteal: number;
  fireRes: number;
  frostRes: number;
  shadowRes: number;
  holyRes: number;
  lightningRes: number;
  poisonRes: number;
  goldValue: number;
  durability: number;
  affixDescription: string;
}

export const MASTER_DATASET_ITEMS_PART_2: MasterDatasetItem_2[] = [
  {
    id: 'item_ds_p2_0001',
    name: 'Artifact Weapon Blade Series 2-1',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 22,
    spellPower: 11,
    armorRating: 6,
    maxHp: 33,
    maxEnergy: 21,
    critChance: 6.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 1,
    fireRes: 1,
    frostRes: 1,
    shadowRes: 1,
    holyRes: 1,
    lightningRes: 1,
    poisonRes: 1,
    goldValue: 60,
    durability: 101,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-1.'
  },
  {
    id: 'item_ds_p2_0002',
    name: 'Artifact Weapon Blade Series 2-2',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 24,
    spellPower: 12,
    armorRating: 7,
    maxHp: 36,
    maxEnergy: 22,
    critChance: 7.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 2,
    fireRes: 2,
    frostRes: 2,
    shadowRes: 2,
    holyRes: 2,
    lightningRes: 2,
    poisonRes: 2,
    goldValue: 70,
    durability: 102,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-2.'
  },
  {
    id: 'item_ds_p2_0003',
    name: 'Artifact Weapon Blade Series 2-3',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 26,
    spellPower: 13,
    armorRating: 8,
    maxHp: 39,
    maxEnergy: 23,
    critChance: 8.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 3,
    fireRes: 3,
    frostRes: 3,
    shadowRes: 3,
    holyRes: 3,
    lightningRes: 3,
    poisonRes: 3,
    goldValue: 80,
    durability: 103,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-3.'
  },
  {
    id: 'item_ds_p2_0004',
    name: 'Artifact Weapon Blade Series 2-4',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 28,
    spellPower: 14,
    armorRating: 9,
    maxHp: 42,
    maxEnergy: 24,
    critChance: 9.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 4,
    fireRes: 4,
    frostRes: 4,
    shadowRes: 4,
    holyRes: 4,
    lightningRes: 4,
    poisonRes: 4,
    goldValue: 90,
    durability: 104,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-4.'
  },
  {
    id: 'item_ds_p2_0005',
    name: 'Artifact Weapon Blade Series 2-5',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 30,
    spellPower: 15,
    armorRating: 10,
    maxHp: 45,
    maxEnergy: 25,
    critChance: 10.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 5,
    fireRes: 5,
    frostRes: 5,
    shadowRes: 5,
    holyRes: 5,
    lightningRes: 5,
    poisonRes: 5,
    goldValue: 100,
    durability: 105,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-5.'
  },
  {
    id: 'item_ds_p2_0006',
    name: 'Artifact Weapon Blade Series 2-6',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 32,
    spellPower: 16,
    armorRating: 11,
    maxHp: 48,
    maxEnergy: 26,
    critChance: 11.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 6,
    fireRes: 6,
    frostRes: 6,
    shadowRes: 6,
    holyRes: 6,
    lightningRes: 6,
    poisonRes: 6,
    goldValue: 110,
    durability: 106,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-6.'
  },
  {
    id: 'item_ds_p2_0007',
    name: 'Artifact Weapon Blade Series 2-7',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 34,
    spellPower: 17,
    armorRating: 12,
    maxHp: 51,
    maxEnergy: 27,
    critChance: 12.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 7,
    fireRes: 7,
    frostRes: 7,
    shadowRes: 7,
    holyRes: 7,
    lightningRes: 7,
    poisonRes: 7,
    goldValue: 120,
    durability: 107,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-7.'
  },
  {
    id: 'item_ds_p2_0008',
    name: 'Artifact Weapon Blade Series 2-8',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 36,
    spellPower: 18,
    armorRating: 13,
    maxHp: 54,
    maxEnergy: 28,
    critChance: 13.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 0,
    fireRes: 8,
    frostRes: 8,
    shadowRes: 8,
    holyRes: 8,
    lightningRes: 8,
    poisonRes: 8,
    goldValue: 130,
    durability: 108,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-8.'
  },
  {
    id: 'item_ds_p2_0009',
    name: 'Artifact Weapon Blade Series 2-9',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 38,
    spellPower: 19,
    armorRating: 14,
    maxHp: 57,
    maxEnergy: 29,
    critChance: 14.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 1,
    fireRes: 9,
    frostRes: 9,
    shadowRes: 9,
    holyRes: 9,
    lightningRes: 9,
    poisonRes: 9,
    goldValue: 140,
    durability: 109,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-9.'
  },
  {
    id: 'item_ds_p2_0010',
    name: 'Artifact Weapon Blade Series 2-10',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 40,
    spellPower: 20,
    armorRating: 15,
    maxHp: 60,
    maxEnergy: 30,
    critChance: 15.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 2,
    fireRes: 10,
    frostRes: 10,
    shadowRes: 10,
    holyRes: 10,
    lightningRes: 10,
    poisonRes: 10,
    goldValue: 150,
    durability: 110,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-10.'
  },
  {
    id: 'item_ds_p2_0011',
    name: 'Artifact Weapon Blade Series 2-11',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 42,
    spellPower: 21,
    armorRating: 16,
    maxHp: 63,
    maxEnergy: 31,
    critChance: 16.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 3,
    fireRes: 11,
    frostRes: 11,
    shadowRes: 11,
    holyRes: 11,
    lightningRes: 11,
    poisonRes: 11,
    goldValue: 160,
    durability: 111,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-11.'
  },
  {
    id: 'item_ds_p2_0012',
    name: 'Artifact Weapon Blade Series 2-12',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 44,
    spellPower: 22,
    armorRating: 17,
    maxHp: 66,
    maxEnergy: 32,
    critChance: 17.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 4,
    fireRes: 12,
    frostRes: 12,
    shadowRes: 12,
    holyRes: 12,
    lightningRes: 12,
    poisonRes: 12,
    goldValue: 170,
    durability: 112,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-12.'
  },
  {
    id: 'item_ds_p2_0013',
    name: 'Artifact Weapon Blade Series 2-13',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 46,
    spellPower: 23,
    armorRating: 18,
    maxHp: 69,
    maxEnergy: 33,
    critChance: 18.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 5,
    fireRes: 13,
    frostRes: 13,
    shadowRes: 13,
    holyRes: 13,
    lightningRes: 13,
    poisonRes: 13,
    goldValue: 180,
    durability: 113,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-13.'
  },
  {
    id: 'item_ds_p2_0014',
    name: 'Artifact Weapon Blade Series 2-14',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 48,
    spellPower: 24,
    armorRating: 19,
    maxHp: 72,
    maxEnergy: 34,
    critChance: 19.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 6,
    fireRes: 14,
    frostRes: 14,
    shadowRes: 14,
    holyRes: 14,
    lightningRes: 14,
    poisonRes: 14,
    goldValue: 190,
    durability: 114,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-14.'
  },
  {
    id: 'item_ds_p2_0015',
    name: 'Artifact Weapon Blade Series 2-15',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 50,
    spellPower: 25,
    armorRating: 20,
    maxHp: 75,
    maxEnergy: 35,
    critChance: 5.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 7,
    fireRes: 15,
    frostRes: 15,
    shadowRes: 15,
    holyRes: 15,
    lightningRes: 15,
    poisonRes: 15,
    goldValue: 200,
    durability: 115,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-15.'
  },
  {
    id: 'item_ds_p2_0016',
    name: 'Artifact Weapon Blade Series 2-16',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 52,
    spellPower: 26,
    armorRating: 21,
    maxHp: 78,
    maxEnergy: 36,
    critChance: 6.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 0,
    fireRes: 16,
    frostRes: 16,
    shadowRes: 16,
    holyRes: 16,
    lightningRes: 16,
    poisonRes: 16,
    goldValue: 210,
    durability: 116,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-16.'
  },
  {
    id: 'item_ds_p2_0017',
    name: 'Artifact Weapon Blade Series 2-17',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 54,
    spellPower: 27,
    armorRating: 22,
    maxHp: 81,
    maxEnergy: 37,
    critChance: 7.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 1,
    fireRes: 17,
    frostRes: 17,
    shadowRes: 17,
    holyRes: 17,
    lightningRes: 17,
    poisonRes: 17,
    goldValue: 220,
    durability: 117,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-17.'
  },
  {
    id: 'item_ds_p2_0018',
    name: 'Artifact Weapon Blade Series 2-18',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 56,
    spellPower: 28,
    armorRating: 23,
    maxHp: 84,
    maxEnergy: 38,
    critChance: 8.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 2,
    fireRes: 18,
    frostRes: 18,
    shadowRes: 18,
    holyRes: 18,
    lightningRes: 18,
    poisonRes: 18,
    goldValue: 230,
    durability: 118,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-18.'
  },
  {
    id: 'item_ds_p2_0019',
    name: 'Artifact Weapon Blade Series 2-19',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 58,
    spellPower: 29,
    armorRating: 24,
    maxHp: 87,
    maxEnergy: 39,
    critChance: 9.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 3,
    fireRes: 19,
    frostRes: 19,
    shadowRes: 19,
    holyRes: 19,
    lightningRes: 19,
    poisonRes: 19,
    goldValue: 240,
    durability: 119,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-19.'
  },
  {
    id: 'item_ds_p2_0020',
    name: 'Artifact Weapon Blade Series 2-20',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 60,
    spellPower: 30,
    armorRating: 5,
    maxHp: 90,
    maxEnergy: 40,
    critChance: 10.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 4,
    fireRes: 20,
    frostRes: 20,
    shadowRes: 20,
    holyRes: 0,
    lightningRes: 0,
    poisonRes: 0,
    goldValue: 250,
    durability: 120,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-20.'
  },
  {
    id: 'item_ds_p2_0021',
    name: 'Artifact Weapon Blade Series 2-21',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 62,
    spellPower: 31,
    armorRating: 6,
    maxHp: 93,
    maxEnergy: 41,
    critChance: 11.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 5,
    fireRes: 21,
    frostRes: 21,
    shadowRes: 21,
    holyRes: 1,
    lightningRes: 1,
    poisonRes: 1,
    goldValue: 260,
    durability: 121,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-21.'
  },
  {
    id: 'item_ds_p2_0022',
    name: 'Artifact Weapon Blade Series 2-22',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 64,
    spellPower: 32,
    armorRating: 7,
    maxHp: 96,
    maxEnergy: 42,
    critChance: 12.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 6,
    fireRes: 22,
    frostRes: 22,
    shadowRes: 22,
    holyRes: 2,
    lightningRes: 2,
    poisonRes: 2,
    goldValue: 270,
    durability: 122,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-22.'
  },
  {
    id: 'item_ds_p2_0023',
    name: 'Artifact Weapon Blade Series 2-23',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 66,
    spellPower: 33,
    armorRating: 8,
    maxHp: 99,
    maxEnergy: 43,
    critChance: 13.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 7,
    fireRes: 23,
    frostRes: 23,
    shadowRes: 23,
    holyRes: 3,
    lightningRes: 3,
    poisonRes: 3,
    goldValue: 280,
    durability: 123,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-23.'
  },
  {
    id: 'item_ds_p2_0024',
    name: 'Artifact Weapon Blade Series 2-24',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 68,
    spellPower: 34,
    armorRating: 9,
    maxHp: 102,
    maxEnergy: 44,
    critChance: 14.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 0,
    fireRes: 24,
    frostRes: 24,
    shadowRes: 24,
    holyRes: 4,
    lightningRes: 4,
    poisonRes: 4,
    goldValue: 290,
    durability: 124,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-24.'
  },
  {
    id: 'item_ds_p2_0025',
    name: 'Artifact Weapon Blade Series 2-25',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 70,
    spellPower: 35,
    armorRating: 10,
    maxHp: 105,
    maxEnergy: 45,
    critChance: 15.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 1,
    fireRes: 0,
    frostRes: 0,
    shadowRes: 25,
    holyRes: 5,
    lightningRes: 5,
    poisonRes: 5,
    goldValue: 300,
    durability: 125,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-25.'
  },
  {
    id: 'item_ds_p2_0026',
    name: 'Artifact Weapon Blade Series 2-26',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 72,
    spellPower: 36,
    armorRating: 11,
    maxHp: 108,
    maxEnergy: 46,
    critChance: 16.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 2,
    fireRes: 1,
    frostRes: 1,
    shadowRes: 26,
    holyRes: 6,
    lightningRes: 6,
    poisonRes: 6,
    goldValue: 310,
    durability: 126,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-26.'
  },
  {
    id: 'item_ds_p2_0027',
    name: 'Artifact Weapon Blade Series 2-27',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 74,
    spellPower: 37,
    armorRating: 12,
    maxHp: 111,
    maxEnergy: 47,
    critChance: 17.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 3,
    fireRes: 2,
    frostRes: 2,
    shadowRes: 27,
    holyRes: 7,
    lightningRes: 7,
    poisonRes: 7,
    goldValue: 320,
    durability: 127,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-27.'
  },
  {
    id: 'item_ds_p2_0028',
    name: 'Artifact Weapon Blade Series 2-28',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 76,
    spellPower: 38,
    armorRating: 13,
    maxHp: 114,
    maxEnergy: 48,
    critChance: 18.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 4,
    fireRes: 3,
    frostRes: 3,
    shadowRes: 28,
    holyRes: 8,
    lightningRes: 8,
    poisonRes: 8,
    goldValue: 330,
    durability: 128,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-28.'
  },
  {
    id: 'item_ds_p2_0029',
    name: 'Artifact Weapon Blade Series 2-29',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 1,
    reqLevel: 1,
    attackPower: 78,
    spellPower: 39,
    armorRating: 14,
    maxHp: 117,
    maxEnergy: 49,
    critChance: 19.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 5,
    fireRes: 4,
    frostRes: 4,
    shadowRes: 29,
    holyRes: 9,
    lightningRes: 9,
    poisonRes: 9,
    goldValue: 340,
    durability: 129,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-29.'
  },
  {
    id: 'item_ds_p2_0030',
    name: 'Artifact Weapon Blade Series 2-30',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 80,
    spellPower: 40,
    armorRating: 15,
    maxHp: 120,
    maxEnergy: 50,
    critChance: 5.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 6,
    fireRes: 5,
    frostRes: 5,
    shadowRes: 0,
    holyRes: 10,
    lightningRes: 10,
    poisonRes: 10,
    goldValue: 350,
    durability: 130,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-30.'
  },
  {
    id: 'item_ds_p2_0031',
    name: 'Artifact Weapon Blade Series 2-31',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 82,
    spellPower: 41,
    armorRating: 16,
    maxHp: 123,
    maxEnergy: 51,
    critChance: 6.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 7,
    fireRes: 6,
    frostRes: 6,
    shadowRes: 1,
    holyRes: 11,
    lightningRes: 11,
    poisonRes: 11,
    goldValue: 360,
    durability: 131,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-31.'
  },
  {
    id: 'item_ds_p2_0032',
    name: 'Artifact Weapon Blade Series 2-32',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 84,
    spellPower: 42,
    armorRating: 17,
    maxHp: 126,
    maxEnergy: 52,
    critChance: 7.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 0,
    fireRes: 7,
    frostRes: 7,
    shadowRes: 2,
    holyRes: 12,
    lightningRes: 12,
    poisonRes: 12,
    goldValue: 370,
    durability: 132,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-32.'
  },
  {
    id: 'item_ds_p2_0033',
    name: 'Artifact Weapon Blade Series 2-33',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 86,
    spellPower: 43,
    armorRating: 18,
    maxHp: 129,
    maxEnergy: 53,
    critChance: 8.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 1,
    fireRes: 8,
    frostRes: 8,
    shadowRes: 3,
    holyRes: 13,
    lightningRes: 13,
    poisonRes: 13,
    goldValue: 380,
    durability: 133,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-33.'
  },
  {
    id: 'item_ds_p2_0034',
    name: 'Artifact Weapon Blade Series 2-34',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 88,
    spellPower: 44,
    armorRating: 19,
    maxHp: 132,
    maxEnergy: 54,
    critChance: 9.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 2,
    fireRes: 9,
    frostRes: 9,
    shadowRes: 4,
    holyRes: 14,
    lightningRes: 14,
    poisonRes: 14,
    goldValue: 390,
    durability: 134,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-34.'
  },
  {
    id: 'item_ds_p2_0035',
    name: 'Artifact Weapon Blade Series 2-35',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 90,
    spellPower: 45,
    armorRating: 20,
    maxHp: 135,
    maxEnergy: 55,
    critChance: 10.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 3,
    fireRes: 10,
    frostRes: 10,
    shadowRes: 5,
    holyRes: 15,
    lightningRes: 15,
    poisonRes: 15,
    goldValue: 400,
    durability: 135,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-35.'
  },
  {
    id: 'item_ds_p2_0036',
    name: 'Artifact Weapon Blade Series 2-36',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 92,
    spellPower: 46,
    armorRating: 21,
    maxHp: 138,
    maxEnergy: 56,
    critChance: 11.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 4,
    fireRes: 11,
    frostRes: 11,
    shadowRes: 6,
    holyRes: 16,
    lightningRes: 16,
    poisonRes: 16,
    goldValue: 410,
    durability: 136,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-36.'
  },
  {
    id: 'item_ds_p2_0037',
    name: 'Artifact Weapon Blade Series 2-37',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 94,
    spellPower: 47,
    armorRating: 22,
    maxHp: 141,
    maxEnergy: 57,
    critChance: 12.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 5,
    fireRes: 12,
    frostRes: 12,
    shadowRes: 7,
    holyRes: 17,
    lightningRes: 17,
    poisonRes: 17,
    goldValue: 420,
    durability: 137,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-37.'
  },
  {
    id: 'item_ds_p2_0038',
    name: 'Artifact Weapon Blade Series 2-38',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 96,
    spellPower: 48,
    armorRating: 23,
    maxHp: 144,
    maxEnergy: 58,
    critChance: 13.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 6,
    fireRes: 13,
    frostRes: 13,
    shadowRes: 8,
    holyRes: 18,
    lightningRes: 18,
    poisonRes: 18,
    goldValue: 430,
    durability: 138,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-38.'
  },
  {
    id: 'item_ds_p2_0039',
    name: 'Artifact Weapon Blade Series 2-39',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 98,
    spellPower: 49,
    armorRating: 24,
    maxHp: 147,
    maxEnergy: 59,
    critChance: 14.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 7,
    fireRes: 14,
    frostRes: 14,
    shadowRes: 9,
    holyRes: 19,
    lightningRes: 19,
    poisonRes: 19,
    goldValue: 440,
    durability: 139,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-39.'
  },
  {
    id: 'item_ds_p2_0040',
    name: 'Artifact Weapon Blade Series 2-40',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 100,
    spellPower: 50,
    armorRating: 5,
    maxHp: 150,
    maxEnergy: 20,
    critChance: 15.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 0,
    fireRes: 15,
    frostRes: 15,
    shadowRes: 10,
    holyRes: 0,
    lightningRes: 0,
    poisonRes: 0,
    goldValue: 450,
    durability: 140,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-40.'
  },
  {
    id: 'item_ds_p2_0041',
    name: 'Artifact Weapon Blade Series 2-41',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 102,
    spellPower: 51,
    armorRating: 6,
    maxHp: 153,
    maxEnergy: 21,
    critChance: 16.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 1,
    fireRes: 16,
    frostRes: 16,
    shadowRes: 11,
    holyRes: 1,
    lightningRes: 1,
    poisonRes: 1,
    goldValue: 460,
    durability: 141,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-41.'
  },
  {
    id: 'item_ds_p2_0042',
    name: 'Artifact Weapon Blade Series 2-42',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 104,
    spellPower: 52,
    armorRating: 7,
    maxHp: 156,
    maxEnergy: 22,
    critChance: 17.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 2,
    fireRes: 17,
    frostRes: 17,
    shadowRes: 12,
    holyRes: 2,
    lightningRes: 2,
    poisonRes: 2,
    goldValue: 470,
    durability: 142,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-42.'
  },
  {
    id: 'item_ds_p2_0043',
    name: 'Artifact Weapon Blade Series 2-43',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 106,
    spellPower: 53,
    armorRating: 8,
    maxHp: 159,
    maxEnergy: 23,
    critChance: 18.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 3,
    fireRes: 18,
    frostRes: 18,
    shadowRes: 13,
    holyRes: 3,
    lightningRes: 3,
    poisonRes: 3,
    goldValue: 480,
    durability: 143,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-43.'
  },
  {
    id: 'item_ds_p2_0044',
    name: 'Artifact Weapon Blade Series 2-44',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 108,
    spellPower: 54,
    armorRating: 9,
    maxHp: 162,
    maxEnergy: 24,
    critChance: 19.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 4,
    fireRes: 19,
    frostRes: 19,
    shadowRes: 14,
    holyRes: 4,
    lightningRes: 4,
    poisonRes: 4,
    goldValue: 490,
    durability: 144,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-44.'
  },
  {
    id: 'item_ds_p2_0045',
    name: 'Artifact Weapon Blade Series 2-45',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 110,
    spellPower: 55,
    armorRating: 10,
    maxHp: 165,
    maxEnergy: 25,
    critChance: 5.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 5,
    fireRes: 20,
    frostRes: 20,
    shadowRes: 15,
    holyRes: 5,
    lightningRes: 5,
    poisonRes: 5,
    goldValue: 500,
    durability: 145,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-45.'
  },
  {
    id: 'item_ds_p2_0046',
    name: 'Artifact Weapon Blade Series 2-46',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 112,
    spellPower: 56,
    armorRating: 11,
    maxHp: 168,
    maxEnergy: 26,
    critChance: 6.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 6,
    fireRes: 21,
    frostRes: 21,
    shadowRes: 16,
    holyRes: 6,
    lightningRes: 6,
    poisonRes: 6,
    goldValue: 510,
    durability: 146,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-46.'
  },
  {
    id: 'item_ds_p2_0047',
    name: 'Artifact Weapon Blade Series 2-47',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 114,
    spellPower: 57,
    armorRating: 12,
    maxHp: 171,
    maxEnergy: 27,
    critChance: 7.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 7,
    fireRes: 22,
    frostRes: 22,
    shadowRes: 17,
    holyRes: 7,
    lightningRes: 7,
    poisonRes: 7,
    goldValue: 520,
    durability: 147,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-47.'
  },
  {
    id: 'item_ds_p2_0048',
    name: 'Artifact Weapon Blade Series 2-48',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 116,
    spellPower: 58,
    armorRating: 13,
    maxHp: 174,
    maxEnergy: 28,
    critChance: 8.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 0,
    fireRes: 23,
    frostRes: 23,
    shadowRes: 18,
    holyRes: 8,
    lightningRes: 8,
    poisonRes: 8,
    goldValue: 530,
    durability: 148,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-48.'
  },
  {
    id: 'item_ds_p2_0049',
    name: 'Artifact Weapon Blade Series 2-49',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 1,
    attackPower: 118,
    spellPower: 59,
    armorRating: 14,
    maxHp: 177,
    maxEnergy: 29,
    critChance: 9.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 1,
    fireRes: 24,
    frostRes: 24,
    shadowRes: 19,
    holyRes: 9,
    lightningRes: 9,
    poisonRes: 9,
    goldValue: 540,
    durability: 149,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-49.'
  },
  {
    id: 'item_ds_p2_0050',
    name: 'Artifact Weapon Blade Series 2-50',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 2,
    reqLevel: 2,
    attackPower: 120,
    spellPower: 60,
    armorRating: 15,
    maxHp: 180,
    maxEnergy: 30,
    critChance: 10.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 2,
    fireRes: 0,
    frostRes: 0,
    shadowRes: 20,
    holyRes: 10,
    lightningRes: 10,
    poisonRes: 10,
    goldValue: 550,
    durability: 100,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-50.'
  },
  {
    id: 'item_ds_p2_0051',
    name: 'Artifact Weapon Blade Series 2-51',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 2,
    reqLevel: 2,
    attackPower: 122,
    spellPower: 61,
    armorRating: 16,
    maxHp: 183,
    maxEnergy: 31,
    critChance: 11.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 3,
    fireRes: 1,
    frostRes: 1,
    shadowRes: 21,
    holyRes: 11,
    lightningRes: 11,
    poisonRes: 11,
    goldValue: 560,
    durability: 101,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-51.'
  },
  {
    id: 'item_ds_p2_0052',
    name: 'Artifact Weapon Blade Series 2-52',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 2,
    attackPower: 124,
    spellPower: 62,
    armorRating: 17,
    maxHp: 186,
    maxEnergy: 32,
    critChance: 12.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 4,
    fireRes: 2,
    frostRes: 2,
    shadowRes: 22,
    holyRes: 12,
    lightningRes: 12,
    poisonRes: 12,
    goldValue: 570,
    durability: 102,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-52.'
  },
  {
    id: 'item_ds_p2_0053',
    name: 'Artifact Weapon Blade Series 2-53',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 2,
    attackPower: 126,
    spellPower: 63,
    armorRating: 18,
    maxHp: 189,
    maxEnergy: 33,
    critChance: 13.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 5,
    fireRes: 3,
    frostRes: 3,
    shadowRes: 23,
    holyRes: 13,
    lightningRes: 13,
    poisonRes: 13,
    goldValue: 580,
    durability: 103,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-53.'
  },
  {
    id: 'item_ds_p2_0054',
    name: 'Artifact Weapon Blade Series 2-54',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 2,
    reqLevel: 2,
    attackPower: 128,
    spellPower: 64,
    armorRating: 19,
    maxHp: 192,
    maxEnergy: 34,
    critChance: 14.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 6,
    fireRes: 4,
    frostRes: 4,
    shadowRes: 24,
    holyRes: 14,
    lightningRes: 14,
    poisonRes: 14,
    goldValue: 590,
    durability: 104,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-54.'
  },
  {
    id: 'item_ds_p2_0055',
    name: 'Artifact Weapon Blade Series 2-55',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 2,
    reqLevel: 2,
    attackPower: 130,
    spellPower: 65,
    armorRating: 20,
    maxHp: 195,
    maxEnergy: 35,
    critChance: 15.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 7,
    fireRes: 5,
    frostRes: 5,
    shadowRes: 25,
    holyRes: 15,
    lightningRes: 15,
    poisonRes: 15,
    goldValue: 600,
    durability: 105,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-55.'
  },
  {
    id: 'item_ds_p2_0056',
    name: 'Artifact Weapon Blade Series 2-56',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 2,
    attackPower: 132,
    spellPower: 66,
    armorRating: 21,
    maxHp: 198,
    maxEnergy: 36,
    critChance: 16.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 0,
    fireRes: 6,
    frostRes: 6,
    shadowRes: 26,
    holyRes: 16,
    lightningRes: 16,
    poisonRes: 16,
    goldValue: 610,
    durability: 106,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-56.'
  },
  {
    id: 'item_ds_p2_0057',
    name: 'Artifact Weapon Blade Series 2-57',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 2,
    reqLevel: 2,
    attackPower: 134,
    spellPower: 67,
    armorRating: 22,
    maxHp: 201,
    maxEnergy: 37,
    critChance: 17.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 1,
    fireRes: 7,
    frostRes: 7,
    shadowRes: 27,
    holyRes: 17,
    lightningRes: 17,
    poisonRes: 17,
    goldValue: 620,
    durability: 107,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-57.'
  },
  {
    id: 'item_ds_p2_0058',
    name: 'Artifact Weapon Blade Series 2-58',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 2,
    attackPower: 136,
    spellPower: 68,
    armorRating: 23,
    maxHp: 204,
    maxEnergy: 38,
    critChance: 18.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 2,
    fireRes: 8,
    frostRes: 8,
    shadowRes: 28,
    holyRes: 18,
    lightningRes: 18,
    poisonRes: 18,
    goldValue: 630,
    durability: 108,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-58.'
  },
  {
    id: 'item_ds_p2_0059',
    name: 'Artifact Weapon Blade Series 2-59',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 2,
    reqLevel: 2,
    attackPower: 138,
    spellPower: 69,
    armorRating: 24,
    maxHp: 207,
    maxEnergy: 39,
    critChance: 19.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 3,
    fireRes: 9,
    frostRes: 9,
    shadowRes: 29,
    holyRes: 19,
    lightningRes: 19,
    poisonRes: 19,
    goldValue: 640,
    durability: 109,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-59.'
  },
  {
    id: 'item_ds_p2_0060',
    name: 'Artifact Weapon Blade Series 2-60',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 140,
    spellPower: 70,
    armorRating: 5,
    maxHp: 210,
    maxEnergy: 40,
    critChance: 5.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 4,
    fireRes: 10,
    frostRes: 10,
    shadowRes: 0,
    holyRes: 0,
    lightningRes: 0,
    poisonRes: 0,
    goldValue: 650,
    durability: 110,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-60.'
  },
  {
    id: 'item_ds_p2_0061',
    name: 'Artifact Weapon Blade Series 2-61',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 142,
    spellPower: 71,
    armorRating: 6,
    maxHp: 213,
    maxEnergy: 41,
    critChance: 6.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 5,
    fireRes: 11,
    frostRes: 11,
    shadowRes: 1,
    holyRes: 1,
    lightningRes: 1,
    poisonRes: 1,
    goldValue: 660,
    durability: 111,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-61.'
  },
  {
    id: 'item_ds_p2_0062',
    name: 'Artifact Weapon Blade Series 2-62',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 144,
    spellPower: 72,
    armorRating: 7,
    maxHp: 216,
    maxEnergy: 42,
    critChance: 7.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 6,
    fireRes: 12,
    frostRes: 12,
    shadowRes: 2,
    holyRes: 2,
    lightningRes: 2,
    poisonRes: 2,
    goldValue: 670,
    durability: 112,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-62.'
  },
  {
    id: 'item_ds_p2_0063',
    name: 'Artifact Weapon Blade Series 2-63',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 146,
    spellPower: 73,
    armorRating: 8,
    maxHp: 219,
    maxEnergy: 43,
    critChance: 8.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 7,
    fireRes: 13,
    frostRes: 13,
    shadowRes: 3,
    holyRes: 3,
    lightningRes: 3,
    poisonRes: 3,
    goldValue: 680,
    durability: 113,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-63.'
  },
  {
    id: 'item_ds_p2_0064',
    name: 'Artifact Weapon Blade Series 2-64',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 148,
    spellPower: 74,
    armorRating: 9,
    maxHp: 222,
    maxEnergy: 44,
    critChance: 9.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 0,
    fireRes: 14,
    frostRes: 14,
    shadowRes: 4,
    holyRes: 4,
    lightningRes: 4,
    poisonRes: 4,
    goldValue: 690,
    durability: 114,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-64.'
  },
  {
    id: 'item_ds_p2_0065',
    name: 'Artifact Weapon Blade Series 2-65',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 150,
    spellPower: 75,
    armorRating: 10,
    maxHp: 225,
    maxEnergy: 45,
    critChance: 10.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 1,
    fireRes: 15,
    frostRes: 15,
    shadowRes: 5,
    holyRes: 5,
    lightningRes: 5,
    poisonRes: 5,
    goldValue: 700,
    durability: 115,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-65.'
  },
  {
    id: 'item_ds_p2_0066',
    name: 'Artifact Weapon Blade Series 2-66',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 152,
    spellPower: 76,
    armorRating: 11,
    maxHp: 228,
    maxEnergy: 46,
    critChance: 11.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 2,
    fireRes: 16,
    frostRes: 16,
    shadowRes: 6,
    holyRes: 6,
    lightningRes: 6,
    poisonRes: 6,
    goldValue: 710,
    durability: 116,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-66.'
  },
  {
    id: 'item_ds_p2_0067',
    name: 'Artifact Weapon Blade Series 2-67',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 154,
    spellPower: 77,
    armorRating: 12,
    maxHp: 231,
    maxEnergy: 47,
    critChance: 12.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 3,
    fireRes: 17,
    frostRes: 17,
    shadowRes: 7,
    holyRes: 7,
    lightningRes: 7,
    poisonRes: 7,
    goldValue: 720,
    durability: 117,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-67.'
  },
  {
    id: 'item_ds_p2_0068',
    name: 'Artifact Weapon Blade Series 2-68',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 156,
    spellPower: 78,
    armorRating: 13,
    maxHp: 234,
    maxEnergy: 48,
    critChance: 13.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 4,
    fireRes: 18,
    frostRes: 18,
    shadowRes: 8,
    holyRes: 8,
    lightningRes: 8,
    poisonRes: 8,
    goldValue: 730,
    durability: 118,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-68.'
  },
  {
    id: 'item_ds_p2_0069',
    name: 'Artifact Weapon Blade Series 2-69',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 158,
    spellPower: 79,
    armorRating: 14,
    maxHp: 237,
    maxEnergy: 49,
    critChance: 14.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 5,
    fireRes: 19,
    frostRes: 19,
    shadowRes: 9,
    holyRes: 9,
    lightningRes: 9,
    poisonRes: 9,
    goldValue: 740,
    durability: 119,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-69.'
  },
  {
    id: 'item_ds_p2_0070',
    name: 'Artifact Weapon Blade Series 2-70',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 160,
    spellPower: 80,
    armorRating: 15,
    maxHp: 240,
    maxEnergy: 50,
    critChance: 15.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 6,
    fireRes: 20,
    frostRes: 20,
    shadowRes: 10,
    holyRes: 10,
    lightningRes: 10,
    poisonRes: 10,
    goldValue: 750,
    durability: 120,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-70.'
  },
  {
    id: 'item_ds_p2_0071',
    name: 'Artifact Weapon Blade Series 2-71',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 162,
    spellPower: 81,
    armorRating: 16,
    maxHp: 243,
    maxEnergy: 51,
    critChance: 16.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 7,
    fireRes: 21,
    frostRes: 21,
    shadowRes: 11,
    holyRes: 11,
    lightningRes: 11,
    poisonRes: 11,
    goldValue: 760,
    durability: 121,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-71.'
  },
  {
    id: 'item_ds_p2_0072',
    name: 'Artifact Weapon Blade Series 2-72',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 164,
    spellPower: 82,
    armorRating: 17,
    maxHp: 246,
    maxEnergy: 52,
    critChance: 17.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 0,
    fireRes: 22,
    frostRes: 22,
    shadowRes: 12,
    holyRes: 12,
    lightningRes: 12,
    poisonRes: 12,
    goldValue: 770,
    durability: 122,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-72.'
  },
  {
    id: 'item_ds_p2_0073',
    name: 'Artifact Weapon Blade Series 2-73',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 166,
    spellPower: 83,
    armorRating: 18,
    maxHp: 249,
    maxEnergy: 53,
    critChance: 18.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 1,
    fireRes: 23,
    frostRes: 23,
    shadowRes: 13,
    holyRes: 13,
    lightningRes: 13,
    poisonRes: 13,
    goldValue: 780,
    durability: 123,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-73.'
  },
  {
    id: 'item_ds_p2_0074',
    name: 'Artifact Weapon Blade Series 2-74',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 168,
    spellPower: 84,
    armorRating: 19,
    maxHp: 252,
    maxEnergy: 54,
    critChance: 19.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 2,
    fireRes: 24,
    frostRes: 24,
    shadowRes: 14,
    holyRes: 14,
    lightningRes: 14,
    poisonRes: 14,
    goldValue: 790,
    durability: 124,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-74.'
  },
  {
    id: 'item_ds_p2_0075',
    name: 'Artifact Weapon Blade Series 2-75',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 170,
    spellPower: 85,
    armorRating: 20,
    maxHp: 255,
    maxEnergy: 55,
    critChance: 5.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 3,
    fireRes: 0,
    frostRes: 0,
    shadowRes: 15,
    holyRes: 15,
    lightningRes: 15,
    poisonRes: 15,
    goldValue: 800,
    durability: 125,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-75.'
  },
  {
    id: 'item_ds_p2_0076',
    name: 'Artifact Weapon Blade Series 2-76',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 172,
    spellPower: 86,
    armorRating: 21,
    maxHp: 258,
    maxEnergy: 56,
    critChance: 6.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 4,
    fireRes: 1,
    frostRes: 1,
    shadowRes: 16,
    holyRes: 16,
    lightningRes: 16,
    poisonRes: 16,
    goldValue: 810,
    durability: 126,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-76.'
  },
  {
    id: 'item_ds_p2_0077',
    name: 'Artifact Weapon Blade Series 2-77',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 174,
    spellPower: 87,
    armorRating: 22,
    maxHp: 261,
    maxEnergy: 57,
    critChance: 7.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 5,
    fireRes: 2,
    frostRes: 2,
    shadowRes: 17,
    holyRes: 17,
    lightningRes: 17,
    poisonRes: 17,
    goldValue: 820,
    durability: 127,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-77.'
  },
  {
    id: 'item_ds_p2_0078',
    name: 'Artifact Weapon Blade Series 2-78',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 176,
    spellPower: 88,
    armorRating: 23,
    maxHp: 264,
    maxEnergy: 58,
    critChance: 8.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 6,
    fireRes: 3,
    frostRes: 3,
    shadowRes: 18,
    holyRes: 18,
    lightningRes: 18,
    poisonRes: 18,
    goldValue: 830,
    durability: 128,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-78.'
  },
  {
    id: 'item_ds_p2_0079',
    name: 'Artifact Weapon Blade Series 2-79',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 178,
    spellPower: 89,
    armorRating: 24,
    maxHp: 267,
    maxEnergy: 59,
    critChance: 9.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 7,
    fireRes: 4,
    frostRes: 4,
    shadowRes: 19,
    holyRes: 19,
    lightningRes: 19,
    poisonRes: 19,
    goldValue: 840,
    durability: 129,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-79.'
  },
  {
    id: 'item_ds_p2_0080',
    name: 'Artifact Weapon Blade Series 2-80',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 180,
    spellPower: 90,
    armorRating: 5,
    maxHp: 270,
    maxEnergy: 20,
    critChance: 10.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 0,
    fireRes: 5,
    frostRes: 5,
    shadowRes: 20,
    holyRes: 0,
    lightningRes: 0,
    poisonRes: 0,
    goldValue: 850,
    durability: 130,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-80.'
  },
  {
    id: 'item_ds_p2_0081',
    name: 'Artifact Weapon Blade Series 2-81',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 182,
    spellPower: 91,
    armorRating: 6,
    maxHp: 273,
    maxEnergy: 21,
    critChance: 11.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 1,
    fireRes: 6,
    frostRes: 6,
    shadowRes: 21,
    holyRes: 1,
    lightningRes: 1,
    poisonRes: 1,
    goldValue: 860,
    durability: 131,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-81.'
  },
  {
    id: 'item_ds_p2_0082',
    name: 'Artifact Weapon Blade Series 2-82',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 184,
    spellPower: 92,
    armorRating: 7,
    maxHp: 276,
    maxEnergy: 22,
    critChance: 12.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 2,
    fireRes: 7,
    frostRes: 7,
    shadowRes: 22,
    holyRes: 2,
    lightningRes: 2,
    poisonRes: 2,
    goldValue: 870,
    durability: 132,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-82.'
  },
  {
    id: 'item_ds_p2_0083',
    name: 'Artifact Weapon Blade Series 2-83',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 186,
    spellPower: 93,
    armorRating: 8,
    maxHp: 279,
    maxEnergy: 23,
    critChance: 13.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 3,
    fireRes: 8,
    frostRes: 8,
    shadowRes: 23,
    holyRes: 3,
    lightningRes: 3,
    poisonRes: 3,
    goldValue: 880,
    durability: 133,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-83.'
  },
  {
    id: 'item_ds_p2_0084',
    name: 'Artifact Weapon Blade Series 2-84',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 188,
    spellPower: 94,
    armorRating: 9,
    maxHp: 282,
    maxEnergy: 24,
    critChance: 14.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 4,
    fireRes: 9,
    frostRes: 9,
    shadowRes: 24,
    holyRes: 4,
    lightningRes: 4,
    poisonRes: 4,
    goldValue: 890,
    durability: 134,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-84.'
  },
  {
    id: 'item_ds_p2_0085',
    name: 'Artifact Weapon Blade Series 2-85',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 190,
    spellPower: 95,
    armorRating: 10,
    maxHp: 285,
    maxEnergy: 25,
    critChance: 15.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 5,
    fireRes: 10,
    frostRes: 10,
    shadowRes: 25,
    holyRes: 5,
    lightningRes: 5,
    poisonRes: 5,
    goldValue: 900,
    durability: 135,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-85.'
  },
  {
    id: 'item_ds_p2_0086',
    name: 'Artifact Weapon Blade Series 2-86',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 192,
    spellPower: 96,
    armorRating: 11,
    maxHp: 288,
    maxEnergy: 26,
    critChance: 16.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 6,
    fireRes: 11,
    frostRes: 11,
    shadowRes: 26,
    holyRes: 6,
    lightningRes: 6,
    poisonRes: 6,
    goldValue: 910,
    durability: 136,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-86.'
  },
  {
    id: 'item_ds_p2_0087',
    name: 'Artifact Weapon Blade Series 2-87',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 194,
    spellPower: 97,
    armorRating: 12,
    maxHp: 291,
    maxEnergy: 27,
    critChance: 17.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 7,
    fireRes: 12,
    frostRes: 12,
    shadowRes: 27,
    holyRes: 7,
    lightningRes: 7,
    poisonRes: 7,
    goldValue: 920,
    durability: 137,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-87.'
  },
  {
    id: 'item_ds_p2_0088',
    name: 'Artifact Weapon Blade Series 2-88',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 196,
    spellPower: 98,
    armorRating: 13,
    maxHp: 294,
    maxEnergy: 28,
    critChance: 18.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 0,
    fireRes: 13,
    frostRes: 13,
    shadowRes: 28,
    holyRes: 8,
    lightningRes: 8,
    poisonRes: 8,
    goldValue: 930,
    durability: 138,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-88.'
  },
  {
    id: 'item_ds_p2_0089',
    name: 'Artifact Weapon Blade Series 2-89',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 3,
    reqLevel: 2,
    attackPower: 198,
    spellPower: 99,
    armorRating: 14,
    maxHp: 297,
    maxEnergy: 29,
    critChance: 19.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 1,
    fireRes: 14,
    frostRes: 14,
    shadowRes: 29,
    holyRes: 9,
    lightningRes: 9,
    poisonRes: 9,
    goldValue: 940,
    durability: 139,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-89.'
  },
  {
    id: 'item_ds_p2_0090',
    name: 'Artifact Weapon Blade Series 2-90',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 4,
    reqLevel: 2,
    attackPower: 200,
    spellPower: 100,
    armorRating: 15,
    maxHp: 300,
    maxEnergy: 30,
    critChance: 5.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 2,
    fireRes: 15,
    frostRes: 15,
    shadowRes: 0,
    holyRes: 10,
    lightningRes: 10,
    poisonRes: 10,
    goldValue: 950,
    durability: 140,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-90.'
  },
  {
    id: 'item_ds_p2_0091',
    name: 'Artifact Weapon Blade Series 2-91',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 2,
    attackPower: 202,
    spellPower: 101,
    armorRating: 16,
    maxHp: 303,
    maxEnergy: 31,
    critChance: 6.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 3,
    fireRes: 16,
    frostRes: 16,
    shadowRes: 1,
    holyRes: 11,
    lightningRes: 11,
    poisonRes: 11,
    goldValue: 960,
    durability: 141,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-91.'
  },
  {
    id: 'item_ds_p2_0092',
    name: 'Artifact Weapon Blade Series 2-92',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 2,
    attackPower: 204,
    spellPower: 102,
    armorRating: 17,
    maxHp: 306,
    maxEnergy: 32,
    critChance: 7.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 4,
    fireRes: 17,
    frostRes: 17,
    shadowRes: 2,
    holyRes: 12,
    lightningRes: 12,
    poisonRes: 12,
    goldValue: 970,
    durability: 142,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-92.'
  },
  {
    id: 'item_ds_p2_0093',
    name: 'Artifact Weapon Blade Series 2-93',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 4,
    reqLevel: 2,
    attackPower: 206,
    spellPower: 103,
    armorRating: 18,
    maxHp: 309,
    maxEnergy: 33,
    critChance: 8.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 5,
    fireRes: 18,
    frostRes: 18,
    shadowRes: 3,
    holyRes: 13,
    lightningRes: 13,
    poisonRes: 13,
    goldValue: 980,
    durability: 143,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-93.'
  },
  {
    id: 'item_ds_p2_0094',
    name: 'Artifact Weapon Blade Series 2-94',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 2,
    attackPower: 208,
    spellPower: 104,
    armorRating: 19,
    maxHp: 312,
    maxEnergy: 34,
    critChance: 9.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 6,
    fireRes: 19,
    frostRes: 19,
    shadowRes: 4,
    holyRes: 14,
    lightningRes: 14,
    poisonRes: 14,
    goldValue: 990,
    durability: 144,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-94.'
  },
  {
    id: 'item_ds_p2_0095',
    name: 'Artifact Weapon Blade Series 2-95',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 4,
    reqLevel: 2,
    attackPower: 210,
    spellPower: 105,
    armorRating: 20,
    maxHp: 315,
    maxEnergy: 35,
    critChance: 10.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 7,
    fireRes: 20,
    frostRes: 20,
    shadowRes: 5,
    holyRes: 15,
    lightningRes: 15,
    poisonRes: 15,
    goldValue: 1000,
    durability: 145,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-95.'
  },
  {
    id: 'item_ds_p2_0096',
    name: 'Artifact Weapon Blade Series 2-96',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 4,
    reqLevel: 2,
    attackPower: 212,
    spellPower: 106,
    armorRating: 21,
    maxHp: 318,
    maxEnergy: 36,
    critChance: 11.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 0,
    fireRes: 21,
    frostRes: 21,
    shadowRes: 6,
    holyRes: 16,
    lightningRes: 16,
    poisonRes: 16,
    goldValue: 1010,
    durability: 146,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-96.'
  },
  {
    id: 'item_ds_p2_0097',
    name: 'Artifact Weapon Blade Series 2-97',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 2,
    attackPower: 214,
    spellPower: 107,
    armorRating: 22,
    maxHp: 321,
    maxEnergy: 37,
    critChance: 12.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 1,
    fireRes: 22,
    frostRes: 22,
    shadowRes: 7,
    holyRes: 17,
    lightningRes: 17,
    poisonRes: 17,
    goldValue: 1020,
    durability: 147,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-97.'
  },
  {
    id: 'item_ds_p2_0098',
    name: 'Artifact Weapon Blade Series 2-98',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 2,
    attackPower: 216,
    spellPower: 108,
    armorRating: 23,
    maxHp: 324,
    maxEnergy: 38,
    critChance: 13.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 2,
    fireRes: 23,
    frostRes: 23,
    shadowRes: 8,
    holyRes: 18,
    lightningRes: 18,
    poisonRes: 18,
    goldValue: 1030,
    durability: 148,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-98.'
  },
  {
    id: 'item_ds_p2_0099',
    name: 'Artifact Weapon Blade Series 2-99',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 4,
    reqLevel: 2,
    attackPower: 218,
    spellPower: 109,
    armorRating: 24,
    maxHp: 327,
    maxEnergy: 39,
    critChance: 14.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 3,
    fireRes: 24,
    frostRes: 24,
    shadowRes: 9,
    holyRes: 19,
    lightningRes: 19,
    poisonRes: 19,
    goldValue: 1040,
    durability: 149,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-99.'
  },
  {
    id: 'item_ds_p2_0100',
    name: 'Artifact Weapon Blade Series 2-100',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 220,
    spellPower: 110,
    armorRating: 5,
    maxHp: 330,
    maxEnergy: 40,
    critChance: 15.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 4,
    fireRes: 0,
    frostRes: 0,
    shadowRes: 10,
    holyRes: 0,
    lightningRes: 0,
    poisonRes: 0,
    goldValue: 1050,
    durability: 100,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-100.'
  },
  {
    id: 'item_ds_p2_0101',
    name: 'Artifact Weapon Blade Series 2-101',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 222,
    spellPower: 111,
    armorRating: 6,
    maxHp: 333,
    maxEnergy: 41,
    critChance: 16.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 5,
    fireRes: 1,
    frostRes: 1,
    shadowRes: 11,
    holyRes: 1,
    lightningRes: 1,
    poisonRes: 1,
    goldValue: 1060,
    durability: 101,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-101.'
  },
  {
    id: 'item_ds_p2_0102',
    name: 'Artifact Weapon Blade Series 2-102',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 224,
    spellPower: 112,
    armorRating: 7,
    maxHp: 336,
    maxEnergy: 42,
    critChance: 17.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 6,
    fireRes: 2,
    frostRes: 2,
    shadowRes: 12,
    holyRes: 2,
    lightningRes: 2,
    poisonRes: 2,
    goldValue: 1070,
    durability: 102,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-102.'
  },
  {
    id: 'item_ds_p2_0103',
    name: 'Artifact Weapon Blade Series 2-103',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 226,
    spellPower: 113,
    armorRating: 8,
    maxHp: 339,
    maxEnergy: 43,
    critChance: 18.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 7,
    fireRes: 3,
    frostRes: 3,
    shadowRes: 13,
    holyRes: 3,
    lightningRes: 3,
    poisonRes: 3,
    goldValue: 1080,
    durability: 103,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-103.'
  },
  {
    id: 'item_ds_p2_0104',
    name: 'Artifact Weapon Blade Series 2-104',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 228,
    spellPower: 114,
    armorRating: 9,
    maxHp: 342,
    maxEnergy: 44,
    critChance: 19.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 0,
    fireRes: 4,
    frostRes: 4,
    shadowRes: 14,
    holyRes: 4,
    lightningRes: 4,
    poisonRes: 4,
    goldValue: 1090,
    durability: 104,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-104.'
  },
  {
    id: 'item_ds_p2_0105',
    name: 'Artifact Weapon Blade Series 2-105',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 230,
    spellPower: 115,
    armorRating: 10,
    maxHp: 345,
    maxEnergy: 45,
    critChance: 5.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 1,
    fireRes: 5,
    frostRes: 5,
    shadowRes: 15,
    holyRes: 5,
    lightningRes: 5,
    poisonRes: 5,
    goldValue: 1100,
    durability: 105,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-105.'
  },
  {
    id: 'item_ds_p2_0106',
    name: 'Artifact Weapon Blade Series 2-106',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 232,
    spellPower: 116,
    armorRating: 11,
    maxHp: 348,
    maxEnergy: 46,
    critChance: 6.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 2,
    fireRes: 6,
    frostRes: 6,
    shadowRes: 16,
    holyRes: 6,
    lightningRes: 6,
    poisonRes: 6,
    goldValue: 1110,
    durability: 106,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-106.'
  },
  {
    id: 'item_ds_p2_0107',
    name: 'Artifact Weapon Blade Series 2-107',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 234,
    spellPower: 117,
    armorRating: 12,
    maxHp: 351,
    maxEnergy: 47,
    critChance: 7.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 3,
    fireRes: 7,
    frostRes: 7,
    shadowRes: 17,
    holyRes: 7,
    lightningRes: 7,
    poisonRes: 7,
    goldValue: 1120,
    durability: 107,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-107.'
  },
  {
    id: 'item_ds_p2_0108',
    name: 'Artifact Weapon Blade Series 2-108',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 236,
    spellPower: 118,
    armorRating: 13,
    maxHp: 354,
    maxEnergy: 48,
    critChance: 8.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 4,
    fireRes: 8,
    frostRes: 8,
    shadowRes: 18,
    holyRes: 8,
    lightningRes: 8,
    poisonRes: 8,
    goldValue: 1130,
    durability: 108,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-108.'
  },
  {
    id: 'item_ds_p2_0109',
    name: 'Artifact Weapon Blade Series 2-109',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 238,
    spellPower: 119,
    armorRating: 14,
    maxHp: 357,
    maxEnergy: 49,
    critChance: 9.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 5,
    fireRes: 9,
    frostRes: 9,
    shadowRes: 19,
    holyRes: 9,
    lightningRes: 9,
    poisonRes: 9,
    goldValue: 1140,
    durability: 109,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-109.'
  },
  {
    id: 'item_ds_p2_0110',
    name: 'Artifact Weapon Blade Series 2-110',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 240,
    spellPower: 120,
    armorRating: 15,
    maxHp: 360,
    maxEnergy: 50,
    critChance: 10.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 6,
    fireRes: 10,
    frostRes: 10,
    shadowRes: 20,
    holyRes: 10,
    lightningRes: 10,
    poisonRes: 10,
    goldValue: 1150,
    durability: 110,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-110.'
  },
  {
    id: 'item_ds_p2_0111',
    name: 'Artifact Weapon Blade Series 2-111',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 242,
    spellPower: 121,
    armorRating: 16,
    maxHp: 363,
    maxEnergy: 51,
    critChance: 11.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 7,
    fireRes: 11,
    frostRes: 11,
    shadowRes: 21,
    holyRes: 11,
    lightningRes: 11,
    poisonRes: 11,
    goldValue: 1160,
    durability: 111,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-111.'
  },
  {
    id: 'item_ds_p2_0112',
    name: 'Artifact Weapon Blade Series 2-112',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 244,
    spellPower: 122,
    armorRating: 17,
    maxHp: 366,
    maxEnergy: 52,
    critChance: 12.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 0,
    fireRes: 12,
    frostRes: 12,
    shadowRes: 22,
    holyRes: 12,
    lightningRes: 12,
    poisonRes: 12,
    goldValue: 1170,
    durability: 112,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-112.'
  },
  {
    id: 'item_ds_p2_0113',
    name: 'Artifact Weapon Blade Series 2-113',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 246,
    spellPower: 123,
    armorRating: 18,
    maxHp: 369,
    maxEnergy: 53,
    critChance: 13.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 1,
    fireRes: 13,
    frostRes: 13,
    shadowRes: 23,
    holyRes: 13,
    lightningRes: 13,
    poisonRes: 13,
    goldValue: 1180,
    durability: 113,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-113.'
  },
  {
    id: 'item_ds_p2_0114',
    name: 'Artifact Weapon Blade Series 2-114',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 248,
    spellPower: 124,
    armorRating: 19,
    maxHp: 372,
    maxEnergy: 54,
    critChance: 14.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 2,
    fireRes: 14,
    frostRes: 14,
    shadowRes: 24,
    holyRes: 14,
    lightningRes: 14,
    poisonRes: 14,
    goldValue: 1190,
    durability: 114,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-114.'
  },
  {
    id: 'item_ds_p2_0115',
    name: 'Artifact Weapon Blade Series 2-115',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 250,
    spellPower: 125,
    armorRating: 20,
    maxHp: 375,
    maxEnergy: 55,
    critChance: 15.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 3,
    fireRes: 15,
    frostRes: 15,
    shadowRes: 25,
    holyRes: 15,
    lightningRes: 15,
    poisonRes: 15,
    goldValue: 1200,
    durability: 115,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-115.'
  },
  {
    id: 'item_ds_p2_0116',
    name: 'Artifact Weapon Blade Series 2-116',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 252,
    spellPower: 126,
    armorRating: 21,
    maxHp: 378,
    maxEnergy: 56,
    critChance: 16.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 4,
    fireRes: 16,
    frostRes: 16,
    shadowRes: 26,
    holyRes: 16,
    lightningRes: 16,
    poisonRes: 16,
    goldValue: 1210,
    durability: 116,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-116.'
  },
  {
    id: 'item_ds_p2_0117',
    name: 'Artifact Weapon Blade Series 2-117',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 254,
    spellPower: 127,
    armorRating: 22,
    maxHp: 381,
    maxEnergy: 57,
    critChance: 17.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 5,
    fireRes: 17,
    frostRes: 17,
    shadowRes: 27,
    holyRes: 17,
    lightningRes: 17,
    poisonRes: 17,
    goldValue: 1220,
    durability: 117,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-117.'
  },
  {
    id: 'item_ds_p2_0118',
    name: 'Artifact Weapon Blade Series 2-118',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 256,
    spellPower: 128,
    armorRating: 23,
    maxHp: 384,
    maxEnergy: 58,
    critChance: 18.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 6,
    fireRes: 18,
    frostRes: 18,
    shadowRes: 28,
    holyRes: 18,
    lightningRes: 18,
    poisonRes: 18,
    goldValue: 1230,
    durability: 118,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-118.'
  },
  {
    id: 'item_ds_p2_0119',
    name: 'Artifact Weapon Blade Series 2-119',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 4,
    reqLevel: 3,
    attackPower: 258,
    spellPower: 129,
    armorRating: 24,
    maxHp: 387,
    maxEnergy: 59,
    critChance: 19.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 7,
    fireRes: 19,
    frostRes: 19,
    shadowRes: 29,
    holyRes: 19,
    lightningRes: 19,
    poisonRes: 19,
    goldValue: 1240,
    durability: 119,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-119.'
  },
  {
    id: 'item_ds_p2_0120',
    name: 'Artifact Weapon Blade Series 2-120',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 260,
    spellPower: 130,
    armorRating: 5,
    maxHp: 390,
    maxEnergy: 20,
    critChance: 5.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 0,
    fireRes: 20,
    frostRes: 20,
    shadowRes: 0,
    holyRes: 0,
    lightningRes: 0,
    poisonRes: 0,
    goldValue: 1250,
    durability: 120,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-120.'
  },
  {
    id: 'item_ds_p2_0121',
    name: 'Artifact Weapon Blade Series 2-121',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 262,
    spellPower: 131,
    armorRating: 6,
    maxHp: 393,
    maxEnergy: 21,
    critChance: 6.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 1,
    fireRes: 21,
    frostRes: 21,
    shadowRes: 1,
    holyRes: 1,
    lightningRes: 1,
    poisonRes: 1,
    goldValue: 1260,
    durability: 121,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-121.'
  },
  {
    id: 'item_ds_p2_0122',
    name: 'Artifact Weapon Blade Series 2-122',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 264,
    spellPower: 132,
    armorRating: 7,
    maxHp: 396,
    maxEnergy: 22,
    critChance: 7.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 2,
    fireRes: 22,
    frostRes: 22,
    shadowRes: 2,
    holyRes: 2,
    lightningRes: 2,
    poisonRes: 2,
    goldValue: 1270,
    durability: 122,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-122.'
  },
  {
    id: 'item_ds_p2_0123',
    name: 'Artifact Weapon Blade Series 2-123',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 266,
    spellPower: 133,
    armorRating: 8,
    maxHp: 399,
    maxEnergy: 23,
    critChance: 8.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 3,
    fireRes: 23,
    frostRes: 23,
    shadowRes: 3,
    holyRes: 3,
    lightningRes: 3,
    poisonRes: 3,
    goldValue: 1280,
    durability: 123,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-123.'
  },
  {
    id: 'item_ds_p2_0124',
    name: 'Artifact Weapon Blade Series 2-124',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 268,
    spellPower: 134,
    armorRating: 9,
    maxHp: 402,
    maxEnergy: 24,
    critChance: 9.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 4,
    fireRes: 24,
    frostRes: 24,
    shadowRes: 4,
    holyRes: 4,
    lightningRes: 4,
    poisonRes: 4,
    goldValue: 1290,
    durability: 124,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-124.'
  },
  {
    id: 'item_ds_p2_0125',
    name: 'Artifact Weapon Blade Series 2-125',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 270,
    spellPower: 135,
    armorRating: 10,
    maxHp: 405,
    maxEnergy: 25,
    critChance: 10.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 5,
    fireRes: 0,
    frostRes: 0,
    shadowRes: 5,
    holyRes: 5,
    lightningRes: 5,
    poisonRes: 5,
    goldValue: 1300,
    durability: 125,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-125.'
  },
  {
    id: 'item_ds_p2_0126',
    name: 'Artifact Weapon Blade Series 2-126',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 272,
    spellPower: 136,
    armorRating: 11,
    maxHp: 408,
    maxEnergy: 26,
    critChance: 11.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 6,
    fireRes: 1,
    frostRes: 1,
    shadowRes: 6,
    holyRes: 6,
    lightningRes: 6,
    poisonRes: 6,
    goldValue: 1310,
    durability: 126,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-126.'
  },
  {
    id: 'item_ds_p2_0127',
    name: 'Artifact Weapon Blade Series 2-127',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 274,
    spellPower: 137,
    armorRating: 12,
    maxHp: 411,
    maxEnergy: 27,
    critChance: 12.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 7,
    fireRes: 2,
    frostRes: 2,
    shadowRes: 7,
    holyRes: 7,
    lightningRes: 7,
    poisonRes: 7,
    goldValue: 1320,
    durability: 127,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-127.'
  },
  {
    id: 'item_ds_p2_0128',
    name: 'Artifact Weapon Blade Series 2-128',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 276,
    spellPower: 138,
    armorRating: 13,
    maxHp: 414,
    maxEnergy: 28,
    critChance: 13.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 0,
    fireRes: 3,
    frostRes: 3,
    shadowRes: 8,
    holyRes: 8,
    lightningRes: 8,
    poisonRes: 8,
    goldValue: 1330,
    durability: 128,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-128.'
  },
  {
    id: 'item_ds_p2_0129',
    name: 'Artifact Weapon Blade Series 2-129',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 278,
    spellPower: 139,
    armorRating: 14,
    maxHp: 417,
    maxEnergy: 29,
    critChance: 14.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 1,
    fireRes: 4,
    frostRes: 4,
    shadowRes: 9,
    holyRes: 9,
    lightningRes: 9,
    poisonRes: 9,
    goldValue: 1340,
    durability: 129,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-129.'
  },
  {
    id: 'item_ds_p2_0130',
    name: 'Artifact Weapon Blade Series 2-130',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 280,
    spellPower: 140,
    armorRating: 15,
    maxHp: 420,
    maxEnergy: 30,
    critChance: 15.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 2,
    fireRes: 5,
    frostRes: 5,
    shadowRes: 10,
    holyRes: 10,
    lightningRes: 10,
    poisonRes: 10,
    goldValue: 1350,
    durability: 130,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-130.'
  },
  {
    id: 'item_ds_p2_0131',
    name: 'Artifact Weapon Blade Series 2-131',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 282,
    spellPower: 141,
    armorRating: 16,
    maxHp: 423,
    maxEnergy: 31,
    critChance: 16.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 3,
    fireRes: 6,
    frostRes: 6,
    shadowRes: 11,
    holyRes: 11,
    lightningRes: 11,
    poisonRes: 11,
    goldValue: 1360,
    durability: 131,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-131.'
  },
  {
    id: 'item_ds_p2_0132',
    name: 'Artifact Weapon Blade Series 2-132',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 284,
    spellPower: 142,
    armorRating: 17,
    maxHp: 426,
    maxEnergy: 32,
    critChance: 17.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 4,
    fireRes: 7,
    frostRes: 7,
    shadowRes: 12,
    holyRes: 12,
    lightningRes: 12,
    poisonRes: 12,
    goldValue: 1370,
    durability: 132,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-132.'
  },
  {
    id: 'item_ds_p2_0133',
    name: 'Artifact Weapon Blade Series 2-133',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 286,
    spellPower: 143,
    armorRating: 18,
    maxHp: 429,
    maxEnergy: 33,
    critChance: 18.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 5,
    fireRes: 8,
    frostRes: 8,
    shadowRes: 13,
    holyRes: 13,
    lightningRes: 13,
    poisonRes: 13,
    goldValue: 1380,
    durability: 133,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-133.'
  },
  {
    id: 'item_ds_p2_0134',
    name: 'Artifact Weapon Blade Series 2-134',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 288,
    spellPower: 144,
    armorRating: 19,
    maxHp: 432,
    maxEnergy: 34,
    critChance: 19.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 6,
    fireRes: 9,
    frostRes: 9,
    shadowRes: 14,
    holyRes: 14,
    lightningRes: 14,
    poisonRes: 14,
    goldValue: 1390,
    durability: 134,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-134.'
  },
  {
    id: 'item_ds_p2_0135',
    name: 'Artifact Weapon Blade Series 2-135',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 290,
    spellPower: 145,
    armorRating: 20,
    maxHp: 435,
    maxEnergy: 35,
    critChance: 5.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 7,
    fireRes: 10,
    frostRes: 10,
    shadowRes: 15,
    holyRes: 15,
    lightningRes: 15,
    poisonRes: 15,
    goldValue: 1400,
    durability: 135,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-135.'
  },
  {
    id: 'item_ds_p2_0136',
    name: 'Artifact Weapon Blade Series 2-136',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 292,
    spellPower: 146,
    armorRating: 21,
    maxHp: 438,
    maxEnergy: 36,
    critChance: 6.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 0,
    fireRes: 11,
    frostRes: 11,
    shadowRes: 16,
    holyRes: 16,
    lightningRes: 16,
    poisonRes: 16,
    goldValue: 1410,
    durability: 136,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-136.'
  },
  {
    id: 'item_ds_p2_0137',
    name: 'Artifact Weapon Blade Series 2-137',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 294,
    spellPower: 147,
    armorRating: 22,
    maxHp: 441,
    maxEnergy: 37,
    critChance: 7.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 1,
    fireRes: 12,
    frostRes: 12,
    shadowRes: 17,
    holyRes: 17,
    lightningRes: 17,
    poisonRes: 17,
    goldValue: 1420,
    durability: 137,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-137.'
  },
  {
    id: 'item_ds_p2_0138',
    name: 'Artifact Weapon Blade Series 2-138',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 296,
    spellPower: 148,
    armorRating: 23,
    maxHp: 444,
    maxEnergy: 38,
    critChance: 8.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 2,
    fireRes: 13,
    frostRes: 13,
    shadowRes: 18,
    holyRes: 18,
    lightningRes: 18,
    poisonRes: 18,
    goldValue: 1430,
    durability: 138,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-138.'
  },
  {
    id: 'item_ds_p2_0139',
    name: 'Artifact Weapon Blade Series 2-139',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 298,
    spellPower: 149,
    armorRating: 24,
    maxHp: 447,
    maxEnergy: 39,
    critChance: 9.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 3,
    fireRes: 14,
    frostRes: 14,
    shadowRes: 19,
    holyRes: 19,
    lightningRes: 19,
    poisonRes: 19,
    goldValue: 1440,
    durability: 139,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-139.'
  },
  {
    id: 'item_ds_p2_0140',
    name: 'Artifact Weapon Blade Series 2-140',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 300,
    spellPower: 150,
    armorRating: 5,
    maxHp: 450,
    maxEnergy: 40,
    critChance: 10.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 4,
    fireRes: 15,
    frostRes: 15,
    shadowRes: 20,
    holyRes: 0,
    lightningRes: 0,
    poisonRes: 0,
    goldValue: 1450,
    durability: 140,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-140.'
  },
  {
    id: 'item_ds_p2_0141',
    name: 'Artifact Weapon Blade Series 2-141',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 302,
    spellPower: 151,
    armorRating: 6,
    maxHp: 453,
    maxEnergy: 41,
    critChance: 11.0,
    critMult: 1.6,
    moveSpeed: 1,
    lifeSteal: 5,
    fireRes: 16,
    frostRes: 16,
    shadowRes: 21,
    holyRes: 1,
    lightningRes: 1,
    poisonRes: 1,
    goldValue: 1460,
    durability: 141,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-141.'
  },
  {
    id: 'item_ds_p2_0142',
    name: 'Artifact Weapon Blade Series 2-142',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 304,
    spellPower: 152,
    armorRating: 7,
    maxHp: 456,
    maxEnergy: 42,
    critChance: 12.0,
    critMult: 1.7,
    moveSpeed: 2,
    lifeSteal: 6,
    fireRes: 17,
    frostRes: 17,
    shadowRes: 22,
    holyRes: 2,
    lightningRes: 2,
    poisonRes: 2,
    goldValue: 1470,
    durability: 142,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-142.'
  },
  {
    id: 'item_ds_p2_0143',
    name: 'Artifact Weapon Blade Series 2-143',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 306,
    spellPower: 153,
    armorRating: 8,
    maxHp: 459,
    maxEnergy: 43,
    critChance: 13.0,
    critMult: 1.8,
    moveSpeed: 3,
    lifeSteal: 7,
    fireRes: 18,
    frostRes: 18,
    shadowRes: 23,
    holyRes: 3,
    lightningRes: 3,
    poisonRes: 3,
    goldValue: 1480,
    durability: 143,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-143.'
  },
  {
    id: 'item_ds_p2_0144',
    name: 'Artifact Weapon Blade Series 2-144',
    slot: 'MainHand',
    rarity: 'Epic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 308,
    spellPower: 154,
    armorRating: 9,
    maxHp: 462,
    maxEnergy: 44,
    critChance: 14.0,
    critMult: 1.9,
    moveSpeed: 4,
    lifeSteal: 0,
    fireRes: 19,
    frostRes: 19,
    shadowRes: 24,
    holyRes: 4,
    lightningRes: 4,
    poisonRes: 4,
    goldValue: 1490,
    durability: 144,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-144.'
  },
  {
    id: 'item_ds_p2_0145',
    name: 'Artifact Weapon Blade Series 2-145',
    slot: 'TwoHand',
    rarity: 'Mythic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 310,
    spellPower: 155,
    armorRating: 10,
    maxHp: 465,
    maxEnergy: 45,
    critChance: 15.0,
    critMult: 2.0,
    moveSpeed: 5,
    lifeSteal: 1,
    fireRes: 20,
    frostRes: 20,
    shadowRes: 25,
    holyRes: 5,
    lightningRes: 5,
    poisonRes: 5,
    goldValue: 1500,
    durability: 145,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-145.'
  },
  {
    id: 'item_ds_p2_0146',
    name: 'Artifact Weapon Blade Series 2-146',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 312,
    spellPower: 156,
    armorRating: 11,
    maxHp: 468,
    maxEnergy: 46,
    critChance: 16.0,
    critMult: 2.1,
    moveSpeed: 6,
    lifeSteal: 2,
    fireRes: 21,
    frostRes: 21,
    shadowRes: 26,
    holyRes: 6,
    lightningRes: 6,
    poisonRes: 6,
    goldValue: 1510,
    durability: 146,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-146.'
  },
  {
    id: 'item_ds_p2_0147',
    name: 'Artifact Weapon Blade Series 2-147',
    slot: 'TwoHand',
    rarity: 'Epic',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 314,
    spellPower: 157,
    armorRating: 12,
    maxHp: 471,
    maxEnergy: 47,
    critChance: 17.0,
    critMult: 2.2,
    moveSpeed: 7,
    lifeSteal: 3,
    fireRes: 22,
    frostRes: 22,
    shadowRes: 27,
    holyRes: 7,
    lightningRes: 7,
    poisonRes: 7,
    goldValue: 1520,
    durability: 147,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-147.'
  },
  {
    id: 'item_ds_p2_0148',
    name: 'Artifact Weapon Blade Series 2-148',
    slot: 'MainHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 316,
    spellPower: 158,
    armorRating: 13,
    maxHp: 474,
    maxEnergy: 48,
    critChance: 18.0,
    critMult: 2.3,
    moveSpeed: 8,
    lifeSteal: 4,
    fireRes: 23,
    frostRes: 23,
    shadowRes: 28,
    holyRes: 8,
    lightningRes: 8,
    poisonRes: 8,
    goldValue: 1530,
    durability: 148,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-148.'
  },
  {
    id: 'item_ds_p2_0149',
    name: 'Artifact Weapon Blade Series 2-149',
    slot: 'TwoHand',
    rarity: 'Rare',
    itemLevel: 5,
    reqLevel: 3,
    attackPower: 318,
    spellPower: 159,
    armorRating: 14,
    maxHp: 477,
    maxEnergy: 49,
    critChance: 19.0,
    critMult: 2.4,
    moveSpeed: 9,
    lifeSteal: 5,
    fireRes: 24,
    frostRes: 24,
    shadowRes: 29,
    holyRes: 9,
    lightningRes: 9,
    poisonRes: 9,
    goldValue: 1540,
    durability: 149,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-149.'
  },
  {
    id: 'item_ds_p2_0150',
    name: 'Artifact Weapon Blade Series 2-150',
    slot: 'MainHand',
    rarity: 'Mythic',
    itemLevel: 6,
    reqLevel: 4,
    attackPower: 320,
    spellPower: 160,
    armorRating: 15,
    maxHp: 480,
    maxEnergy: 50,
    critChance: 5.0,
    critMult: 1.5,
    moveSpeed: 0,
    lifeSteal: 6,
    fireRes: 0,
    frostRes: 0,
    shadowRes: 0,
    holyRes: 10,
    lightningRes: 10,
    poisonRes: 10,
    goldValue: 1550,
    durability: 100,
    affixDescription: 'Imbued with ancient combat enchantments tier 2-150.'
  }
];
