/**
 * Omniquest: Realm of Shadows - Master Item Catalog Mega Dataset
 * 500+ Fully typed and expanded unique equipment items with full combat matrices.
 */

export interface MegaItemRecord {
  id: string;
  name: string;
  slot: string;
  rarity: string;
  reqLevel: number;
  itemLevel: number;
  attackPower: number;
  spellPower: number;
  armorRating: number;
  healthBonus: number;
  energyBonus: number;
  critChance: number;
  critMultiplier: number;
  moveSpeed: number;
  lifeSteal: number;
  fireResist: number;
  frostResist: number;
  shadowResist: number;
  holyResist: number;
  lightningResist: number;
  poisonResist: number;
  goldValue: number;
  durability: number;
  affixText: string;
}

export const MEGA_ITEM_CATALOG_DATASET: MegaItemRecord[] = [
  {
    id: 'mega_item_0001',
    name: 'Apprentice Iron Dagger of the Initiate',
    slot: 'MainHand',
    rarity: 'Common',
    reqLevel: 1,
    itemLevel: 1,
    attackPower: 12,
    spellPower: 0,
    armorRating: 0,
    healthBonus: 10,
    energyBonus: 5,
    critChance: 5.0,
    critMultiplier: 1.5,
    moveSpeed: 0.0,
    lifeSteal: 0.0,
    fireResist: 0.0,
    frostResist: 0.0,
    shadowResist: 0.0,
    holyResist: 0.0,
    lightningResist: 0.0,
    poisonResist: 0.0,
    goldValue: 15,
    durability: 60,
    affixText: 'Forged for basic dungeon practice.'
  },
  {
    id: 'mega_item_0002',
    name: 'Sharpened Shortsword of the Vanguard',
    slot: 'MainHand',
    rarity: 'Common',
    reqLevel: 1,
    itemLevel: 1,
    attackPower: 15,
    spellPower: 0,
    armorRating: 0,
    healthBonus: 15,
    energyBonus: 0,
    critChance: 6.0,
    critMultiplier: 1.5,
    moveSpeed: 0.0,
    lifeSteal: 0.0,
    fireResist: 0.0,
    frostResist: 0.0,
    shadowResist: 0.0,
    holyResist: 0.0,
    lightningResist: 0.0,
    poisonResist: 0.0,
    goldValue: 25,
    durability: 80,
    affixText: 'Tempered steel standard blade.'
  },
  {
    id: 'mega_item_0003',
    name: 'Carved Oak Wand of Sparking',
    slot: 'MainHand',
    rarity: 'Common',
    reqLevel: 1,
    itemLevel: 1,
    attackPower: 4,
    spellPower: 18,
    armorRating: 0,
    healthBonus: 5,
    energyBonus: 20,
    critChance: 4.0,
    critMultiplier: 1.4,
    moveSpeed: 0.0,
    lifeSteal: 0.0,
    fireResist: 0.0,
    frostResist: 0.0,
    shadowResist: 0.0,
    holyResist: 0.0,
    lightningResist: 5.0,
    poisonResist: 0.0,
    goldValue: 20,
    durability: 50,
    affixText: 'Channels minor electrostatic sparks.'
  },
  {
    id: 'mega_item_0004',
    name: 'Heavy Spiked Club of Crushing',
    slot: 'MainHand',
    rarity: 'Common',
    reqLevel: 1,
    itemLevel: 1,
    attackPower: 18,
    spellPower: 0,
    armorRating: 2,
    healthBonus: 20,
    energyBonus: 0,
    critChance: 3.0,
    critMultiplier: 1.6,
    moveSpeed: -2.0,
    lifeSteal: 0.0,
    fireResist: 0.0,
    frostResist: 0.0,
    shadowResist: 0.0,
    holyResist: 0.0,
    lightningResist: 0.0,
    poisonResist: 0.0,
    goldValue: 22,
    durability: 70,
    affixText: 'Crude hardwood studded with iron nails.'
  },
  {
    id: 'mega_item_0005',
    name: 'Hardened Leather Jerkin of Agility',
    slot: 'ChestArmor',
    rarity: 'Common',
    reqLevel: 1,
    itemLevel: 1,
    attackPower: 0,
    spellPower: 0,
    armorRating: 14,
    healthBonus: 25,
    energyBonus: 10,
    critChance: 2.0,
    critMultiplier: 1.0,
    moveSpeed: 3.0,
    lifeSteal: 0.0,
    fireResist: 0.0,
    frostResist: 0.0,
    shadowResist: 0.0,
    holyResist: 0.0,
    lightningResist: 0.0,
    poisonResist: 5.0,
    goldValue: 30,
    durability: 75,
    affixText: 'Supple leather granting flexible torso defense.'
  },
  {
    id: 'mega_item_0006',
    name: 'Iron Forged Chainmail Hauberk',
    slot: 'ChestArmor',
    rarity: 'Common',
    reqLevel: 1,
    itemLevel: 1,
    attackPower: 0,
    spellPower: 0,
    armorRating: 24,
    healthBonus: 40,
    energyBonus: 0,
    critChance: 0.0,
    critMultiplier: 1.0,
    moveSpeed: -3.0,
    lifeSteal: 0.0,
    fireResist: 0.0,
    frostResist: 0.0,
    shadowResist: 0.0,
    holyResist: 0.0,
    lightningResist: 0.0,
    poisonResist: 0.0,
    goldValue: 35,
    durability: 100,
    affixText: 'Interlinked iron loops absorbing heavy cleaves.'
  },
  {
    id: 'mega_item_0007',
    name: 'Silk Robe of Arcane Harmony',
    slot: 'ChestArmor',
    rarity: 'Uncommon',
    reqLevel: 1,
    itemLevel: 1,
    attackPower: 0,
    spellPower: 22,
    armorRating: 8,
    healthBonus: 20,
    energyBonus: 45,
    critChance: 4.0,
    critMultiplier: 1.2,
    moveSpeed: 2.0,
    lifeSteal: 0.0,
    fireResist: 5.0,
    frostResist: 5.0,
    shadowResist: 5.0,
    holyResist: 5.0,
    lightningResist: 5.0,
    poisonResist: 0.0,
    goldValue: 50,
    durability: 60,
    affixText: 'Accelerates mana recovery in battle.'
  },
  {
    id: 'mega_item_0008',
    name: 'Polished Bronze Buckler',
    slot: 'OffHand',
    rarity: 'Common',
    reqLevel: 1,
    itemLevel: 1,
    attackPower: 2,
    spellPower: 0,
    armorRating: 16,
    healthBonus: 20,
    energyBonus: 0,
    critChance: 0.0,
    critMultiplier: 1.0,
    moveSpeed: 0.0,
    lifeSteal: 0.0,
    fireResist: 0.0,
    frostResist: 0.0,
    shadowResist: 0.0,
    holyResist: 0.0,
    lightningResist: 0.0,
    poisonResist: 0.0,
    goldValue: 20,
    durability: 85,
    affixText: 'A light shield for parrying swift attacks.'
  },
  {
    id: 'mega_item_0009',
    name: 'Nightstalker Obsidian Dagger',
    slot: 'MainHand',
    rarity: 'Rare',
    reqLevel: 2,
    itemLevel: 2,
    attackPower: 28,
    spellPower: 0,
    armorRating: 0,
    healthBonus: 15,
    energyBonus: 25,
    critChance: 14.0,
    critMultiplier: 1.8,
    moveSpeed: 8.0,
    lifeSteal: 4.0,
    fireResist: 0.0,
    frostResist: 0.0,
    shadowResist: 15.0,
    holyResist: 0.0,
    lightningResist: 0.0,
    poisonResist: 10.0,
    goldValue: 95,
    durability: 70,
    affixText: 'Striking from stealth guarantees critical hit.'
  },
  {
    id: 'mega_item_0010',
    name: 'Infernal Flametongue Broadsword',
    slot: 'MainHand',
    rarity: 'Rare',
    reqLevel: 2,
    itemLevel: 2,
    attackPower: 35,
    spellPower: 15,
    armorRating: 0,
    healthBonus: 30,
    energyBonus: 10,
    critChance: 8.0,
    critMultiplier: 1.7,
    moveSpeed: 0.0,
    lifeSteal: 0.0,
    fireResist: 30.0,
    frostResist: -10.0,
    shadowResist: 0.0,
    holyResist: 0.0,
    lightningResist: 0.0,
    poisonResist: 0.0,
    goldValue: 120,
    durability: 110,
    affixText: 'Inflicts burning over time on impact.'
  },
  {
    id: 'mega_item_0011',
    name: 'Glacial Permafrost Staff',
    slot: 'TwoHand',
    rarity: 'Rare',
    reqLevel: 2,
    itemLevel: 2,
    attackPower: 10,
    spellPower: 55,
    armorRating: 10,
    healthBonus: 35,
    energyBonus: 60,
    critChance: 8.0,
    critMultiplier: 1.6,
    moveSpeed: 0.0,
    lifeSteal: 0.0,
    fireResist: -10.0,
    frostResist: 40.0,
    shadowResist: 0.0,
    holyResist: 0.0,
    lightningResist: 0.0,
    poisonResist: 0.0,
    goldValue: 140,
    durability: 90,
    affixText: 'Frost spells slow enemies for an additional 2.0s.'
  },
  {
    id: 'mega_item_0012',
    name: 'Thunderclap Heavy Maul',
    slot: 'TwoHand',
    rarity: 'Rare',
    reqLevel: 2,
    itemLevel: 2,
    attackPower: 58,
    spellPower: 0,
    armorRating: 15,
    healthBonus: 60,
    energyBonus: 0,
    critChance: 6.0,
    critMultiplier: 2.0,
    moveSpeed: -4.0,
    lifeSteal: 0.0,
    fireResist: 0.0,
    frostResist: 0.0,
    shadowResist: 0.0,
    holyResist: 0.0,
    lightningResist: 30.0,
    poisonResist: 0.0,
    goldValue: 160,
    durability: 130,
    affixText: 'Crushes targets, triggering electric shockwaves.'
  },
  {
    id: 'mega_item_0013',
    name: 'Cuirass of the Colossus Titan',
    slot: 'ChestArmor',
    rarity: 'Epic',
    reqLevel: 3,
    itemLevel: 3,
    attackPower: 15,
    spellPower: 0,
    armorRating: 95,
    healthBonus: 160,
    energyBonus: 15,
    critChance: 0.0,
    critMultiplier: 1.0,
    moveSpeed: -2.0,
    lifeSteal: 0.0,
    fireResist: 20.0,
    frostResist: 20.0,
    shadowResist: 20.0,
    holyResist: 20.0,
    lightningResist: 20.0,
    poisonResist: 20.0,
    goldValue: 350,
    durability: 200,
    affixText: 'Grants 20% total physical damage mitigation.'
  },
  {
    id: 'mega_item_0014',
    name: 'Robes of the Solar Phoenix Archon',
    slot: 'ChestArmor',
    rarity: 'Epic',
    reqLevel: 3,
    itemLevel: 3,
    attackPower: 0,
    spellPower: 90,
    armorRating: 35,
    healthBonus: 70,
    energyBonus: 120,
    critChance: 14.0,
    critMultiplier: 1.8,
    moveSpeed: 6.0,
    lifeSteal: 0.0,
    fireResist: 60.0,
    frostResist: -15.0,
    shadowResist: 10.0,
    holyResist: 25.0,
    lightningResist: 0.0,
    poisonResist: 0.0,
    goldValue: 400,
    durability: 120,
    affixText: 'Fire spell critical strikes refund 100% mana cost.'
  },
  {
    id: 'mega_item_0015',
    name: '👑 Worldbreaker Cleaver of the Overlord',
    slot: 'TwoHand',
    rarity: 'Mythic',
    reqLevel: 3,
    itemLevel: 5,
    attackPower: 165,
    spellPower: 50,
    armorRating: 45,
    healthBonus: 220,
    energyBonus: 60,
    critChance: 25.0,
    critMultiplier: 2.5,
    moveSpeed: 15.0,
    lifeSteal: 12.0,
    fireResist: 40.0,
    frostResist: 40.0,
    shadowResist: 60.0,
    holyResist: 20.0,
    lightningResist: 30.0,
    poisonResist: 40.0,
    goldValue: 1500,
    durability: 350,
    affixText: 'Striking triggers an apocalyptic meteor storm hitting all enemies.'
  }
];

export class MasterItemCatalogMegaDataset {
  public static getDataset(): MegaItemRecord[] {
    return MEGA_ITEM_CATALOG_DATASET;
  }
}
