/**
 * Omniquest: Realm of Shadows - Master SpellBook Dataset Part 2
 * Exhaustive spell incantations matrix.
 */

export interface MasterDatasetSpell_2 {
  id: string;
  name: string;
  school: string;
  reqLevel: number;
  manaCost: number;
  cooldown: number;
  castTime: number;
  damage: number;
  atkScale: number;
  spScale: number;
  critMult: number;
  aoeRadius: number;
  range: number;
  speed: number;
  soundCue: string;
  color: string;
  particle: string;
  description: string;
}

export const MASTER_DATASET_SPELLS_PART_2: MasterDatasetSpell_2[] = [
  {
    id: 'sp_ds_p2_0001',
    name: 'Elemental Incantation Formula 2-1',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 11,
    cooldown: 1.0,
    castTime: 0,
    damage: 43,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 51,
    range: 201,
    speed: 251,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0002',
    name: 'Elemental Incantation Formula 2-2',
    school: 'Shadow',
    reqLevel: 1,
    manaCost: 12,
    cooldown: 1.5,
    castTime: 0,
    damage: 46,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 52,
    range: 202,
    speed: 252,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0003',
    name: 'Elemental Incantation Formula 2-3',
    school: 'Frost',
    reqLevel: 1,
    manaCost: 13,
    cooldown: 2.0,
    castTime: 0.4,
    damage: 49,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 53,
    range: 203,
    speed: 253,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0004',
    name: 'Elemental Incantation Formula 2-4',
    school: 'Fire',
    reqLevel: 1,
    manaCost: 14,
    cooldown: 2.5,
    castTime: 0,
    damage: 52,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 54,
    range: 204,
    speed: 254,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0005',
    name: 'Elemental Incantation Formula 2-5',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 15,
    cooldown: 3.0,
    castTime: 0,
    damage: 55,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 55,
    range: 205,
    speed: 255,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0006',
    name: 'Elemental Incantation Formula 2-6',
    school: 'Frost',
    reqLevel: 1,
    manaCost: 16,
    cooldown: 3.5,
    castTime: 0.4,
    damage: 58,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 56,
    range: 206,
    speed: 256,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0007',
    name: 'Elemental Incantation Formula 2-7',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 17,
    cooldown: 4.0,
    castTime: 0,
    damage: 61,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 57,
    range: 207,
    speed: 257,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0008',
    name: 'Elemental Incantation Formula 2-8',
    school: 'Fire',
    reqLevel: 1,
    manaCost: 18,
    cooldown: 0.5,
    castTime: 0,
    damage: 64,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 58,
    range: 208,
    speed: 258,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0009',
    name: 'Elemental Incantation Formula 2-9',
    school: 'Frost',
    reqLevel: 1,
    manaCost: 19,
    cooldown: 1.0,
    castTime: 0.4,
    damage: 67,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 59,
    range: 209,
    speed: 259,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0010',
    name: 'Elemental Incantation Formula 2-10',
    school: 'Shadow',
    reqLevel: 1,
    manaCost: 20,
    cooldown: 1.5,
    castTime: 0,
    damage: 70,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 60,
    range: 210,
    speed: 260,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0011',
    name: 'Elemental Incantation Formula 2-11',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 21,
    cooldown: 2.0,
    castTime: 0,
    damage: 73,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 61,
    range: 211,
    speed: 261,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0012',
    name: 'Elemental Incantation Formula 2-12',
    school: 'Fire',
    reqLevel: 1,
    manaCost: 22,
    cooldown: 2.5,
    castTime: 0.4,
    damage: 76,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 62,
    range: 212,
    speed: 262,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0013',
    name: 'Elemental Incantation Formula 2-13',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 23,
    cooldown: 3.0,
    castTime: 0,
    damage: 79,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 63,
    range: 213,
    speed: 263,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0014',
    name: 'Elemental Incantation Formula 2-14',
    school: 'Shadow',
    reqLevel: 1,
    manaCost: 24,
    cooldown: 3.5,
    castTime: 0,
    damage: 82,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 64,
    range: 214,
    speed: 264,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0015',
    name: 'Elemental Incantation Formula 2-15',
    school: 'Frost',
    reqLevel: 1,
    manaCost: 25,
    cooldown: 4.0,
    castTime: 0.4,
    damage: 85,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 65,
    range: 215,
    speed: 265,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0016',
    name: 'Elemental Incantation Formula 2-16',
    school: 'Fire',
    reqLevel: 1,
    manaCost: 26,
    cooldown: 0.5,
    castTime: 0,
    damage: 88,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 66,
    range: 216,
    speed: 266,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0017',
    name: 'Elemental Incantation Formula 2-17',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 27,
    cooldown: 1.0,
    castTime: 0,
    damage: 91,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 67,
    range: 217,
    speed: 267,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0018',
    name: 'Elemental Incantation Formula 2-18',
    school: 'Frost',
    reqLevel: 1,
    manaCost: 28,
    cooldown: 1.5,
    castTime: 0.4,
    damage: 94,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 68,
    range: 218,
    speed: 268,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0019',
    name: 'Elemental Incantation Formula 2-19',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 29,
    cooldown: 2.0,
    castTime: 0,
    damage: 97,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 69,
    range: 219,
    speed: 269,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0020',
    name: 'Elemental Incantation Formula 2-20',
    school: 'Fire',
    reqLevel: 1,
    manaCost: 30,
    cooldown: 2.5,
    castTime: 0,
    damage: 100,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 70,
    range: 220,
    speed: 270,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0021',
    name: 'Elemental Incantation Formula 2-21',
    school: 'Frost',
    reqLevel: 1,
    manaCost: 31,
    cooldown: 3.0,
    castTime: 0.4,
    damage: 103,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 71,
    range: 221,
    speed: 271,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0022',
    name: 'Elemental Incantation Formula 2-22',
    school: 'Shadow',
    reqLevel: 1,
    manaCost: 32,
    cooldown: 3.5,
    castTime: 0,
    damage: 106,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 72,
    range: 222,
    speed: 272,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0023',
    name: 'Elemental Incantation Formula 2-23',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 33,
    cooldown: 4.0,
    castTime: 0,
    damage: 109,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 73,
    range: 223,
    speed: 273,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0024',
    name: 'Elemental Incantation Formula 2-24',
    school: 'Fire',
    reqLevel: 1,
    manaCost: 34,
    cooldown: 0.5,
    castTime: 0.4,
    damage: 112,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 74,
    range: 224,
    speed: 274,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0025',
    name: 'Elemental Incantation Formula 2-25',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 35,
    cooldown: 1.0,
    castTime: 0,
    damage: 115,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 75,
    range: 225,
    speed: 275,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0026',
    name: 'Elemental Incantation Formula 2-26',
    school: 'Shadow',
    reqLevel: 1,
    manaCost: 36,
    cooldown: 1.5,
    castTime: 0,
    damage: 118,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 76,
    range: 226,
    speed: 276,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0027',
    name: 'Elemental Incantation Formula 2-27',
    school: 'Frost',
    reqLevel: 1,
    manaCost: 37,
    cooldown: 2.0,
    castTime: 0.4,
    damage: 121,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 77,
    range: 227,
    speed: 277,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0028',
    name: 'Elemental Incantation Formula 2-28',
    school: 'Fire',
    reqLevel: 1,
    manaCost: 38,
    cooldown: 2.5,
    castTime: 0,
    damage: 124,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 78,
    range: 228,
    speed: 278,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0029',
    name: 'Elemental Incantation Formula 2-29',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 39,
    cooldown: 3.0,
    castTime: 0,
    damage: 127,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 79,
    range: 229,
    speed: 279,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0030',
    name: 'Elemental Incantation Formula 2-30',
    school: 'Frost',
    reqLevel: 1,
    manaCost: 40,
    cooldown: 3.5,
    castTime: 0.4,
    damage: 130,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 80,
    range: 230,
    speed: 280,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0031',
    name: 'Elemental Incantation Formula 2-31',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 41,
    cooldown: 4.0,
    castTime: 0,
    damage: 133,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 81,
    range: 231,
    speed: 281,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0032',
    name: 'Elemental Incantation Formula 2-32',
    school: 'Fire',
    reqLevel: 1,
    manaCost: 42,
    cooldown: 0.5,
    castTime: 0,
    damage: 136,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 82,
    range: 232,
    speed: 282,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0033',
    name: 'Elemental Incantation Formula 2-33',
    school: 'Frost',
    reqLevel: 1,
    manaCost: 43,
    cooldown: 1.0,
    castTime: 0.4,
    damage: 139,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 83,
    range: 233,
    speed: 283,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0034',
    name: 'Elemental Incantation Formula 2-34',
    school: 'Shadow',
    reqLevel: 1,
    manaCost: 44,
    cooldown: 1.5,
    castTime: 0,
    damage: 142,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 84,
    range: 234,
    speed: 284,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0035',
    name: 'Elemental Incantation Formula 2-35',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 10,
    cooldown: 2.0,
    castTime: 0,
    damage: 145,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 85,
    range: 235,
    speed: 285,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0036',
    name: 'Elemental Incantation Formula 2-36',
    school: 'Fire',
    reqLevel: 1,
    manaCost: 11,
    cooldown: 2.5,
    castTime: 0.4,
    damage: 148,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 86,
    range: 236,
    speed: 286,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0037',
    name: 'Elemental Incantation Formula 2-37',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 12,
    cooldown: 3.0,
    castTime: 0,
    damage: 151,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 87,
    range: 237,
    speed: 287,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0038',
    name: 'Elemental Incantation Formula 2-38',
    school: 'Shadow',
    reqLevel: 1,
    manaCost: 13,
    cooldown: 3.5,
    castTime: 0,
    damage: 154,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 88,
    range: 238,
    speed: 288,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0039',
    name: 'Elemental Incantation Formula 2-39',
    school: 'Frost',
    reqLevel: 1,
    manaCost: 14,
    cooldown: 4.0,
    castTime: 0.4,
    damage: 157,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 89,
    range: 239,
    speed: 289,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0040',
    name: 'Elemental Incantation Formula 2-40',
    school: 'Fire',
    reqLevel: 1,
    manaCost: 15,
    cooldown: 0.5,
    castTime: 0,
    damage: 160,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 90,
    range: 240,
    speed: 290,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0041',
    name: 'Elemental Incantation Formula 2-41',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 16,
    cooldown: 1.0,
    castTime: 0,
    damage: 163,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 91,
    range: 241,
    speed: 291,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0042',
    name: 'Elemental Incantation Formula 2-42',
    school: 'Frost',
    reqLevel: 1,
    manaCost: 17,
    cooldown: 1.5,
    castTime: 0.4,
    damage: 166,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 92,
    range: 242,
    speed: 292,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0043',
    name: 'Elemental Incantation Formula 2-43',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 18,
    cooldown: 2.0,
    castTime: 0,
    damage: 169,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 93,
    range: 243,
    speed: 293,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0044',
    name: 'Elemental Incantation Formula 2-44',
    school: 'Fire',
    reqLevel: 1,
    manaCost: 19,
    cooldown: 2.5,
    castTime: 0,
    damage: 172,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 94,
    range: 244,
    speed: 294,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0045',
    name: 'Elemental Incantation Formula 2-45',
    school: 'Frost',
    reqLevel: 1,
    manaCost: 20,
    cooldown: 3.0,
    castTime: 0.4,
    damage: 175,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 95,
    range: 245,
    speed: 295,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0046',
    name: 'Elemental Incantation Formula 2-46',
    school: 'Shadow',
    reqLevel: 1,
    manaCost: 21,
    cooldown: 3.5,
    castTime: 0,
    damage: 178,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 96,
    range: 246,
    speed: 296,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0047',
    name: 'Elemental Incantation Formula 2-47',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 22,
    cooldown: 4.0,
    castTime: 0,
    damage: 181,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 97,
    range: 247,
    speed: 297,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0048',
    name: 'Elemental Incantation Formula 2-48',
    school: 'Fire',
    reqLevel: 1,
    manaCost: 23,
    cooldown: 0.5,
    castTime: 0.4,
    damage: 184,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 98,
    range: 248,
    speed: 298,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0049',
    name: 'Elemental Incantation Formula 2-49',
    school: 'Lightning',
    reqLevel: 1,
    manaCost: 24,
    cooldown: 1.0,
    castTime: 0,
    damage: 187,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 99,
    range: 249,
    speed: 299,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0050',
    name: 'Elemental Incantation Formula 2-50',
    school: 'Shadow',
    reqLevel: 2,
    manaCost: 25,
    cooldown: 1.5,
    castTime: 0,
    damage: 190,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 100,
    range: 250,
    speed: 300,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0051',
    name: 'Elemental Incantation Formula 2-51',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 26,
    cooldown: 2.0,
    castTime: 0.4,
    damage: 193,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 101,
    range: 251,
    speed: 301,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0052',
    name: 'Elemental Incantation Formula 2-52',
    school: 'Fire',
    reqLevel: 2,
    manaCost: 27,
    cooldown: 2.5,
    castTime: 0,
    damage: 196,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 102,
    range: 252,
    speed: 302,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0053',
    name: 'Elemental Incantation Formula 2-53',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 28,
    cooldown: 3.0,
    castTime: 0,
    damage: 199,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 103,
    range: 253,
    speed: 303,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0054',
    name: 'Elemental Incantation Formula 2-54',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 29,
    cooldown: 3.5,
    castTime: 0.4,
    damage: 202,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 104,
    range: 254,
    speed: 304,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0055',
    name: 'Elemental Incantation Formula 2-55',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 30,
    cooldown: 4.0,
    castTime: 0,
    damage: 205,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 105,
    range: 255,
    speed: 305,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0056',
    name: 'Elemental Incantation Formula 2-56',
    school: 'Fire',
    reqLevel: 2,
    manaCost: 31,
    cooldown: 0.5,
    castTime: 0,
    damage: 208,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 106,
    range: 256,
    speed: 306,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0057',
    name: 'Elemental Incantation Formula 2-57',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 32,
    cooldown: 1.0,
    castTime: 0.4,
    damage: 211,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 107,
    range: 257,
    speed: 307,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0058',
    name: 'Elemental Incantation Formula 2-58',
    school: 'Shadow',
    reqLevel: 2,
    manaCost: 33,
    cooldown: 1.5,
    castTime: 0,
    damage: 214,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 108,
    range: 258,
    speed: 308,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0059',
    name: 'Elemental Incantation Formula 2-59',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 34,
    cooldown: 2.0,
    castTime: 0,
    damage: 217,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 109,
    range: 259,
    speed: 309,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0060',
    name: 'Elemental Incantation Formula 2-60',
    school: 'Fire',
    reqLevel: 2,
    manaCost: 35,
    cooldown: 2.5,
    castTime: 0.4,
    damage: 220,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 110,
    range: 260,
    speed: 310,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0061',
    name: 'Elemental Incantation Formula 2-61',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 36,
    cooldown: 3.0,
    castTime: 0,
    damage: 223,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 111,
    range: 261,
    speed: 311,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0062',
    name: 'Elemental Incantation Formula 2-62',
    school: 'Shadow',
    reqLevel: 2,
    manaCost: 37,
    cooldown: 3.5,
    castTime: 0,
    damage: 226,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 112,
    range: 262,
    speed: 312,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0063',
    name: 'Elemental Incantation Formula 2-63',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 38,
    cooldown: 4.0,
    castTime: 0.4,
    damage: 229,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 113,
    range: 263,
    speed: 313,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0064',
    name: 'Elemental Incantation Formula 2-64',
    school: 'Fire',
    reqLevel: 2,
    manaCost: 39,
    cooldown: 0.5,
    castTime: 0,
    damage: 232,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 114,
    range: 264,
    speed: 314,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0065',
    name: 'Elemental Incantation Formula 2-65',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 40,
    cooldown: 1.0,
    castTime: 0,
    damage: 235,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 115,
    range: 265,
    speed: 315,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0066',
    name: 'Elemental Incantation Formula 2-66',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 41,
    cooldown: 1.5,
    castTime: 0.4,
    damage: 238,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 116,
    range: 266,
    speed: 316,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0067',
    name: 'Elemental Incantation Formula 2-67',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 42,
    cooldown: 2.0,
    castTime: 0,
    damage: 241,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 117,
    range: 267,
    speed: 317,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0068',
    name: 'Elemental Incantation Formula 2-68',
    school: 'Fire',
    reqLevel: 2,
    manaCost: 43,
    cooldown: 2.5,
    castTime: 0,
    damage: 244,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 118,
    range: 268,
    speed: 318,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0069',
    name: 'Elemental Incantation Formula 2-69',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 44,
    cooldown: 3.0,
    castTime: 0.4,
    damage: 247,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 119,
    range: 269,
    speed: 319,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0070',
    name: 'Elemental Incantation Formula 2-70',
    school: 'Shadow',
    reqLevel: 2,
    manaCost: 10,
    cooldown: 3.5,
    castTime: 0,
    damage: 250,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 120,
    range: 270,
    speed: 320,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0071',
    name: 'Elemental Incantation Formula 2-71',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 11,
    cooldown: 4.0,
    castTime: 0,
    damage: 253,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 121,
    range: 271,
    speed: 321,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0072',
    name: 'Elemental Incantation Formula 2-72',
    school: 'Fire',
    reqLevel: 2,
    manaCost: 12,
    cooldown: 0.5,
    castTime: 0.4,
    damage: 256,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 122,
    range: 272,
    speed: 322,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0073',
    name: 'Elemental Incantation Formula 2-73',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 13,
    cooldown: 1.0,
    castTime: 0,
    damage: 259,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 123,
    range: 273,
    speed: 323,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0074',
    name: 'Elemental Incantation Formula 2-74',
    school: 'Shadow',
    reqLevel: 2,
    manaCost: 14,
    cooldown: 1.5,
    castTime: 0,
    damage: 262,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 124,
    range: 274,
    speed: 324,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0075',
    name: 'Elemental Incantation Formula 2-75',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 15,
    cooldown: 2.0,
    castTime: 0.4,
    damage: 265,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 125,
    range: 275,
    speed: 325,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0076',
    name: 'Elemental Incantation Formula 2-76',
    school: 'Fire',
    reqLevel: 2,
    manaCost: 16,
    cooldown: 2.5,
    castTime: 0,
    damage: 268,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 126,
    range: 276,
    speed: 326,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0077',
    name: 'Elemental Incantation Formula 2-77',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 17,
    cooldown: 3.0,
    castTime: 0,
    damage: 271,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 127,
    range: 277,
    speed: 327,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0078',
    name: 'Elemental Incantation Formula 2-78',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 18,
    cooldown: 3.5,
    castTime: 0.4,
    damage: 274,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 128,
    range: 278,
    speed: 328,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0079',
    name: 'Elemental Incantation Formula 2-79',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 19,
    cooldown: 4.0,
    castTime: 0,
    damage: 277,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 129,
    range: 279,
    speed: 329,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0080',
    name: 'Elemental Incantation Formula 2-80',
    school: 'Fire',
    reqLevel: 2,
    manaCost: 20,
    cooldown: 0.5,
    castTime: 0,
    damage: 280,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 130,
    range: 280,
    speed: 330,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0081',
    name: 'Elemental Incantation Formula 2-81',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 21,
    cooldown: 1.0,
    castTime: 0.4,
    damage: 283,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 131,
    range: 281,
    speed: 331,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0082',
    name: 'Elemental Incantation Formula 2-82',
    school: 'Shadow',
    reqLevel: 2,
    manaCost: 22,
    cooldown: 1.5,
    castTime: 0,
    damage: 286,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 132,
    range: 282,
    speed: 332,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0083',
    name: 'Elemental Incantation Formula 2-83',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 23,
    cooldown: 2.0,
    castTime: 0,
    damage: 289,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 133,
    range: 283,
    speed: 333,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0084',
    name: 'Elemental Incantation Formula 2-84',
    school: 'Fire',
    reqLevel: 2,
    manaCost: 24,
    cooldown: 2.5,
    castTime: 0.4,
    damage: 292,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 134,
    range: 284,
    speed: 334,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0085',
    name: 'Elemental Incantation Formula 2-85',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 25,
    cooldown: 3.0,
    castTime: 0,
    damage: 295,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 135,
    range: 285,
    speed: 335,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0086',
    name: 'Elemental Incantation Formula 2-86',
    school: 'Shadow',
    reqLevel: 2,
    manaCost: 26,
    cooldown: 3.5,
    castTime: 0,
    damage: 298,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 136,
    range: 286,
    speed: 336,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0087',
    name: 'Elemental Incantation Formula 2-87',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 27,
    cooldown: 4.0,
    castTime: 0.4,
    damage: 301,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 137,
    range: 287,
    speed: 337,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0088',
    name: 'Elemental Incantation Formula 2-88',
    school: 'Fire',
    reqLevel: 2,
    manaCost: 28,
    cooldown: 0.5,
    castTime: 0,
    damage: 304,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 138,
    range: 288,
    speed: 338,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0089',
    name: 'Elemental Incantation Formula 2-89',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 29,
    cooldown: 1.0,
    castTime: 0,
    damage: 307,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 139,
    range: 289,
    speed: 339,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0090',
    name: 'Elemental Incantation Formula 2-90',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 30,
    cooldown: 1.5,
    castTime: 0.4,
    damage: 310,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 140,
    range: 290,
    speed: 340,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0091',
    name: 'Elemental Incantation Formula 2-91',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 31,
    cooldown: 2.0,
    castTime: 0,
    damage: 313,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 141,
    range: 291,
    speed: 341,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0092',
    name: 'Elemental Incantation Formula 2-92',
    school: 'Fire',
    reqLevel: 2,
    manaCost: 32,
    cooldown: 2.5,
    castTime: 0,
    damage: 316,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 142,
    range: 292,
    speed: 342,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0093',
    name: 'Elemental Incantation Formula 2-93',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 33,
    cooldown: 3.0,
    castTime: 0.4,
    damage: 319,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 143,
    range: 293,
    speed: 343,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0094',
    name: 'Elemental Incantation Formula 2-94',
    school: 'Shadow',
    reqLevel: 2,
    manaCost: 34,
    cooldown: 3.5,
    castTime: 0,
    damage: 322,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 144,
    range: 294,
    speed: 344,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0095',
    name: 'Elemental Incantation Formula 2-95',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 35,
    cooldown: 4.0,
    castTime: 0,
    damage: 325,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 145,
    range: 295,
    speed: 345,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0096',
    name: 'Elemental Incantation Formula 2-96',
    school: 'Fire',
    reqLevel: 2,
    manaCost: 36,
    cooldown: 0.5,
    castTime: 0.4,
    damage: 328,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 146,
    range: 296,
    speed: 346,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0097',
    name: 'Elemental Incantation Formula 2-97',
    school: 'Lightning',
    reqLevel: 2,
    manaCost: 37,
    cooldown: 1.0,
    castTime: 0,
    damage: 331,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 147,
    range: 297,
    speed: 347,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0098',
    name: 'Elemental Incantation Formula 2-98',
    school: 'Shadow',
    reqLevel: 2,
    manaCost: 38,
    cooldown: 1.5,
    castTime: 0,
    damage: 334,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 148,
    range: 298,
    speed: 348,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0099',
    name: 'Elemental Incantation Formula 2-99',
    school: 'Frost',
    reqLevel: 2,
    manaCost: 39,
    cooldown: 2.0,
    castTime: 0.4,
    damage: 337,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 149,
    range: 299,
    speed: 349,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0100',
    name: 'Elemental Incantation Formula 2-100',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 40,
    cooldown: 2.5,
    castTime: 0,
    damage: 340,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 150,
    range: 300,
    speed: 350,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0101',
    name: 'Elemental Incantation Formula 2-101',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 41,
    cooldown: 3.0,
    castTime: 0,
    damage: 343,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 151,
    range: 301,
    speed: 351,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0102',
    name: 'Elemental Incantation Formula 2-102',
    school: 'Frost',
    reqLevel: 3,
    manaCost: 42,
    cooldown: 3.5,
    castTime: 0.4,
    damage: 346,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 152,
    range: 302,
    speed: 352,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0103',
    name: 'Elemental Incantation Formula 2-103',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 43,
    cooldown: 4.0,
    castTime: 0,
    damage: 349,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 153,
    range: 303,
    speed: 353,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0104',
    name: 'Elemental Incantation Formula 2-104',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 44,
    cooldown: 0.5,
    castTime: 0,
    damage: 352,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 154,
    range: 304,
    speed: 354,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0105',
    name: 'Elemental Incantation Formula 2-105',
    school: 'Frost',
    reqLevel: 3,
    manaCost: 10,
    cooldown: 1.0,
    castTime: 0.4,
    damage: 355,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 155,
    range: 305,
    speed: 355,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0106',
    name: 'Elemental Incantation Formula 2-106',
    school: 'Shadow',
    reqLevel: 3,
    manaCost: 11,
    cooldown: 1.5,
    castTime: 0,
    damage: 358,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 156,
    range: 306,
    speed: 356,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0107',
    name: 'Elemental Incantation Formula 2-107',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 12,
    cooldown: 2.0,
    castTime: 0,
    damage: 361,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 157,
    range: 307,
    speed: 357,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0108',
    name: 'Elemental Incantation Formula 2-108',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 13,
    cooldown: 2.5,
    castTime: 0.4,
    damage: 364,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 158,
    range: 308,
    speed: 358,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0109',
    name: 'Elemental Incantation Formula 2-109',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 14,
    cooldown: 3.0,
    castTime: 0,
    damage: 367,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 159,
    range: 309,
    speed: 359,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0110',
    name: 'Elemental Incantation Formula 2-110',
    school: 'Shadow',
    reqLevel: 3,
    manaCost: 15,
    cooldown: 3.5,
    castTime: 0,
    damage: 370,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 160,
    range: 310,
    speed: 360,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0111',
    name: 'Elemental Incantation Formula 2-111',
    school: 'Frost',
    reqLevel: 3,
    manaCost: 16,
    cooldown: 4.0,
    castTime: 0.4,
    damage: 373,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 161,
    range: 311,
    speed: 361,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0112',
    name: 'Elemental Incantation Formula 2-112',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 17,
    cooldown: 0.5,
    castTime: 0,
    damage: 376,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 162,
    range: 312,
    speed: 362,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0113',
    name: 'Elemental Incantation Formula 2-113',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 18,
    cooldown: 1.0,
    castTime: 0,
    damage: 379,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 163,
    range: 313,
    speed: 363,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0114',
    name: 'Elemental Incantation Formula 2-114',
    school: 'Frost',
    reqLevel: 3,
    manaCost: 19,
    cooldown: 1.5,
    castTime: 0.4,
    damage: 382,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 164,
    range: 314,
    speed: 364,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0115',
    name: 'Elemental Incantation Formula 2-115',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 20,
    cooldown: 2.0,
    castTime: 0,
    damage: 385,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 165,
    range: 315,
    speed: 365,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0116',
    name: 'Elemental Incantation Formula 2-116',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 21,
    cooldown: 2.5,
    castTime: 0,
    damage: 388,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 166,
    range: 316,
    speed: 366,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0117',
    name: 'Elemental Incantation Formula 2-117',
    school: 'Frost',
    reqLevel: 3,
    manaCost: 22,
    cooldown: 3.0,
    castTime: 0.4,
    damage: 391,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 167,
    range: 317,
    speed: 367,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0118',
    name: 'Elemental Incantation Formula 2-118',
    school: 'Shadow',
    reqLevel: 3,
    manaCost: 23,
    cooldown: 3.5,
    castTime: 0,
    damage: 394,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 168,
    range: 318,
    speed: 368,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0119',
    name: 'Elemental Incantation Formula 2-119',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 24,
    cooldown: 4.0,
    castTime: 0,
    damage: 397,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 169,
    range: 319,
    speed: 369,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0120',
    name: 'Elemental Incantation Formula 2-120',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 25,
    cooldown: 0.5,
    castTime: 0.4,
    damage: 400,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 170,
    range: 320,
    speed: 370,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0121',
    name: 'Elemental Incantation Formula 2-121',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 26,
    cooldown: 1.0,
    castTime: 0,
    damage: 403,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 171,
    range: 321,
    speed: 371,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0122',
    name: 'Elemental Incantation Formula 2-122',
    school: 'Shadow',
    reqLevel: 3,
    manaCost: 27,
    cooldown: 1.5,
    castTime: 0,
    damage: 406,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 172,
    range: 322,
    speed: 372,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0123',
    name: 'Elemental Incantation Formula 2-123',
    school: 'Frost',
    reqLevel: 3,
    manaCost: 28,
    cooldown: 2.0,
    castTime: 0.4,
    damage: 409,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 173,
    range: 323,
    speed: 373,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0124',
    name: 'Elemental Incantation Formula 2-124',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 29,
    cooldown: 2.5,
    castTime: 0,
    damage: 412,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 174,
    range: 324,
    speed: 374,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0125',
    name: 'Elemental Incantation Formula 2-125',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 30,
    cooldown: 3.0,
    castTime: 0,
    damage: 415,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 175,
    range: 325,
    speed: 375,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0126',
    name: 'Elemental Incantation Formula 2-126',
    school: 'Frost',
    reqLevel: 3,
    manaCost: 31,
    cooldown: 3.5,
    castTime: 0.4,
    damage: 418,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 176,
    range: 326,
    speed: 376,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0127',
    name: 'Elemental Incantation Formula 2-127',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 32,
    cooldown: 4.0,
    castTime: 0,
    damage: 421,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 177,
    range: 327,
    speed: 377,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0128',
    name: 'Elemental Incantation Formula 2-128',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 33,
    cooldown: 0.5,
    castTime: 0,
    damage: 424,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 178,
    range: 328,
    speed: 378,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0129',
    name: 'Elemental Incantation Formula 2-129',
    school: 'Frost',
    reqLevel: 3,
    manaCost: 34,
    cooldown: 1.0,
    castTime: 0.4,
    damage: 427,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 179,
    range: 329,
    speed: 379,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0130',
    name: 'Elemental Incantation Formula 2-130',
    school: 'Shadow',
    reqLevel: 3,
    manaCost: 35,
    cooldown: 1.5,
    castTime: 0,
    damage: 430,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 180,
    range: 330,
    speed: 380,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0131',
    name: 'Elemental Incantation Formula 2-131',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 36,
    cooldown: 2.0,
    castTime: 0,
    damage: 433,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 181,
    range: 331,
    speed: 381,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0132',
    name: 'Elemental Incantation Formula 2-132',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 37,
    cooldown: 2.5,
    castTime: 0.4,
    damage: 436,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 182,
    range: 332,
    speed: 382,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0133',
    name: 'Elemental Incantation Formula 2-133',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 38,
    cooldown: 3.0,
    castTime: 0,
    damage: 439,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 183,
    range: 333,
    speed: 383,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0134',
    name: 'Elemental Incantation Formula 2-134',
    school: 'Shadow',
    reqLevel: 3,
    manaCost: 39,
    cooldown: 3.5,
    castTime: 0,
    damage: 442,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 184,
    range: 334,
    speed: 384,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0135',
    name: 'Elemental Incantation Formula 2-135',
    school: 'Frost',
    reqLevel: 3,
    manaCost: 40,
    cooldown: 4.0,
    castTime: 0.4,
    damage: 445,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 185,
    range: 335,
    speed: 385,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0136',
    name: 'Elemental Incantation Formula 2-136',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 41,
    cooldown: 0.5,
    castTime: 0,
    damage: 448,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 186,
    range: 336,
    speed: 386,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0137',
    name: 'Elemental Incantation Formula 2-137',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 42,
    cooldown: 1.0,
    castTime: 0,
    damage: 451,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 187,
    range: 337,
    speed: 387,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0138',
    name: 'Elemental Incantation Formula 2-138',
    school: 'Frost',
    reqLevel: 3,
    manaCost: 43,
    cooldown: 1.5,
    castTime: 0.4,
    damage: 454,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 188,
    range: 338,
    speed: 388,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0139',
    name: 'Elemental Incantation Formula 2-139',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 44,
    cooldown: 2.0,
    castTime: 0,
    damage: 457,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 189,
    range: 339,
    speed: 389,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0140',
    name: 'Elemental Incantation Formula 2-140',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 10,
    cooldown: 2.5,
    castTime: 0,
    damage: 460,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 190,
    range: 340,
    speed: 390,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0141',
    name: 'Elemental Incantation Formula 2-141',
    school: 'Frost',
    reqLevel: 3,
    manaCost: 11,
    cooldown: 3.0,
    castTime: 0.4,
    damage: 463,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 191,
    range: 341,
    speed: 391,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0142',
    name: 'Elemental Incantation Formula 2-142',
    school: 'Shadow',
    reqLevel: 3,
    manaCost: 12,
    cooldown: 3.5,
    castTime: 0,
    damage: 466,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 192,
    range: 342,
    speed: 392,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0143',
    name: 'Elemental Incantation Formula 2-143',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 13,
    cooldown: 4.0,
    castTime: 0,
    damage: 469,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 193,
    range: 343,
    speed: 393,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0144',
    name: 'Elemental Incantation Formula 2-144',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 14,
    cooldown: 0.5,
    castTime: 0.4,
    damage: 472,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 194,
    range: 344,
    speed: 394,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0145',
    name: 'Elemental Incantation Formula 2-145',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 15,
    cooldown: 1.0,
    castTime: 0,
    damage: 475,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 195,
    range: 345,
    speed: 395,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0146',
    name: 'Elemental Incantation Formula 2-146',
    school: 'Shadow',
    reqLevel: 3,
    manaCost: 16,
    cooldown: 1.5,
    castTime: 0,
    damage: 478,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 196,
    range: 346,
    speed: 396,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0147',
    name: 'Elemental Incantation Formula 2-147',
    school: 'Frost',
    reqLevel: 3,
    manaCost: 17,
    cooldown: 2.0,
    castTime: 0.4,
    damage: 481,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 197,
    range: 347,
    speed: 397,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0148',
    name: 'Elemental Incantation Formula 2-148',
    school: 'Fire',
    reqLevel: 3,
    manaCost: 18,
    cooldown: 2.5,
    castTime: 0,
    damage: 484,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 198,
    range: 348,
    speed: 398,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0149',
    name: 'Elemental Incantation Formula 2-149',
    school: 'Lightning',
    reqLevel: 3,
    manaCost: 19,
    cooldown: 3.0,
    castTime: 0,
    damage: 487,
    atkScale: 0,
    spScale: 1.8,
    critMult: 2.0,
    aoeRadius: 199,
    range: 349,
    speed: 399,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  },
  {
    id: 'sp_ds_p2_0150',
    name: 'Elemental Incantation Formula 2-150',
    school: 'Frost',
    reqLevel: 4,
    manaCost: 20,
    cooldown: 3.5,
    castTime: 0.4,
    damage: 490,
    atkScale: 1.4,
    spScale: 0,
    critMult: 2.0,
    aoeRadius: 50,
    range: 350,
    speed: 250,
    soundCue: 'fireball_cast',
    color: '#f97316',
    particle: 'spark',
    description: 'Channels primordial energy to strike dungeon targets.'
  }
];
