/**
 * Omniquest: Realm of Shadows - Master Talent Dataset Part 2
 * Exhaustive talent tree node specs.
 */

export interface MasterDatasetTalent_2 {
  id: string;
  heroClass: string;
  branch: string;
  tier: number;
  name: string;
  icon: string;
  maxRank: number;
  bonusAttr: string;
  bonusVal: number;
  isPercent: boolean;
  summary: string;
}

export const MASTER_DATASET_TALENTS_PART_2: MasterDatasetTalent_2[] = [
  {
    id: 'tal_ds_p2_0001',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-1',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0002',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-2',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0003',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-3',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0004',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-4',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0005',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-5',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0006',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-6',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0007',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-7',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0008',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-8',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0009',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-9',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0010',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-10',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0011',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-11',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0012',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-12',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0013',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-13',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0014',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-14',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0015',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-15',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0016',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-16',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0017',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-17',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0018',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-18',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0019',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-19',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0020',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-20',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0021',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-21',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0022',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-22',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0023',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-23',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0024',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-24',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0025',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-25',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0026',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-26',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0027',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-27',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0028',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-28',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0029',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-29',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0030',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-30',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0031',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-31',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0032',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-32',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0033',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-33',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0034',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-34',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0035',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-35',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0036',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-36',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0037',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-37',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0038',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-38',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0039',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-39',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0040',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-40',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0041',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-41',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0042',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-42',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0043',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-43',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0044',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-44',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0045',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-45',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0046',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-46',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0047',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-47',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0048',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-48',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0049',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-49',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0050',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-50',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0051',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-51',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0052',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-52',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0053',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-53',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0054',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-54',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0055',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-55',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0056',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-56',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0057',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-57',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0058',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-58',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0059',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-59',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0060',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-60',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0061',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-61',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0062',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-62',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0063',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-63',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0064',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-64',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0065',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-65',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0066',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-66',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0067',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-67',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0068',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-68',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0069',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-69',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0070',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-70',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0071',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-71',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0072',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-72',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0073',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-73',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0074',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-74',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0075',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-75',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0076',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-76',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0077',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-77',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0078',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-78',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0079',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-79',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0080',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-80',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0081',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-81',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0082',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-82',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0083',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-83',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0084',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-84',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0085',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-85',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0086',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-86',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0087',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-87',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0088',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-88',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0089',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-89',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0090',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-90',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0091',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-91',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0092',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-92',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0093',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-93',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0094',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-94',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0095',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-95',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0096',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-96',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0097',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-97',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0098',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-98',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0099',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-99',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0100',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-100',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0101',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-101',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0102',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-102',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0103',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-103',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0104',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-104',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0105',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-105',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0106',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-106',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0107',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-107',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0108',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-108',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0109',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-109',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0110',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-110',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0111',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-111',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0112',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-112',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0113',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-113',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0114',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-114',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0115',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-115',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0116',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-116',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0117',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-117',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0118',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-118',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0119',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-119',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0120',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-120',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0121',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-121',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0122',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-122',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0123',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-123',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0124',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-124',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0125',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-125',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0126',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-126',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0127',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-127',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0128',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-128',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0129',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-129',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0130',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-130',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0131',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-131',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0132',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-132',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0133',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-133',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0134',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-134',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0135',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-135',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0136',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-136',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0137',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-137',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0138',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-138',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0139',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-139',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0140',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-140',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0141',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-141',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0142',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-142',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0143',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-143',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0144',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 5,
    name: 'Ascension Talent Node 2-144',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0145',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 6,
    name: 'Ascension Talent Node 2-145',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0146',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 7,
    name: 'Ascension Talent Node 2-146',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0147',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 1,
    name: 'Ascension Talent Node 2-147',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0148',
    heroClass: 'Mage',
    branch: 'Mastery Branch 2',
    tier: 2,
    name: 'Ascension Talent Node 2-148',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0149',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 2',
    tier: 3,
    name: 'Ascension Talent Node 2-149',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p2_0150',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 2',
    tier: 4,
    name: 'Ascension Talent Node 2-150',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  }
];
