/**
 * Omniquest: Realm of Shadows - Master Talent Dataset Part 1
 * Exhaustive talent tree node specs.
 */

export interface MasterDatasetTalent_1 {
  id: string;
  heroClass: string;
  branch: string;
  tier: number;
  name: string;
  icon: string;
  maxRank: number;
  bonusAttr: string;
  bonusVal: number;
  isPercent: boolean;
  summary: string;
}

export const MASTER_DATASET_TALENTS_PART_1: MasterDatasetTalent_1[] = [
  {
    id: 'tal_ds_p1_0001',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-1',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0002',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-2',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0003',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-3',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0004',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-4',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0005',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-5',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0006',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-6',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0007',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-7',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0008',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-8',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0009',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-9',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0010',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-10',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0011',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-11',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0012',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-12',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0013',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-13',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0014',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-14',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0015',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-15',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0016',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-16',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0017',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-17',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0018',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-18',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0019',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-19',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0020',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-20',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0021',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-21',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0022',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-22',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0023',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-23',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0024',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-24',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0025',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-25',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0026',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-26',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0027',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-27',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0028',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-28',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0029',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-29',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0030',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-30',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0031',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-31',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0032',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-32',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0033',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-33',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0034',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-34',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0035',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-35',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0036',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-36',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0037',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-37',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0038',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-38',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0039',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-39',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0040',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-40',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0041',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-41',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0042',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-42',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0043',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-43',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0044',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-44',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0045',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-45',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0046',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-46',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0047',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-47',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0048',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-48',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0049',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-49',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0050',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-50',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0051',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-51',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0052',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-52',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0053',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-53',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0054',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-54',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0055',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-55',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0056',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-56',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0057',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-57',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0058',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-58',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0059',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-59',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0060',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-60',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0061',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-61',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0062',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-62',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0063',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-63',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0064',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-64',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0065',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-65',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0066',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-66',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0067',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-67',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0068',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-68',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0069',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-69',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0070',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-70',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0071',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-71',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0072',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-72',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0073',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-73',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0074',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-74',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0075',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-75',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0076',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-76',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0077',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-77',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0078',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-78',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0079',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-79',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0080',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-80',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0081',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-81',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0082',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-82',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0083',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-83',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0084',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-84',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0085',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-85',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0086',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-86',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0087',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-87',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0088',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-88',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0089',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-89',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0090',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-90',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0091',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-91',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0092',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-92',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0093',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-93',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0094',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-94',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0095',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-95',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0096',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-96',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0097',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-97',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0098',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-98',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0099',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-99',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0100',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-100',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0101',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-101',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0102',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-102',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0103',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-103',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0104',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-104',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0105',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-105',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0106',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-106',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0107',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-107',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0108',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-108',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0109',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-109',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0110',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-110',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0111',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-111',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0112',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-112',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0113',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-113',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0114',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-114',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0115',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-115',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0116',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-116',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0117',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-117',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0118',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-118',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0119',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-119',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0120',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-120',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0121',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-121',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0122',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-122',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0123',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-123',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0124',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-124',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0125',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-125',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0126',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-126',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0127',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-127',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0128',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-128',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0129',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-129',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0130',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-130',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0131',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-131',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0132',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-132',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0133',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-133',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0134',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-134',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0135',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-135',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0136',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-136',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0137',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-137',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0138',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-138',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0139',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-139',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0140',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-140',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0141',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-141',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 3,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0142',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-142',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 4,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0143',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-143',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 5,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0144',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 5,
    name: 'Ascension Talent Node 1-144',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 6,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0145',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 6,
    name: 'Ascension Talent Node 1-145',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 7,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0146',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 7,
    name: 'Ascension Talent Node 1-146',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 8,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0147',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 1,
    name: 'Ascension Talent Node 1-147',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 9,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0148',
    heroClass: 'Mage',
    branch: 'Mastery Branch 1',
    tier: 2,
    name: 'Ascension Talent Node 1-148',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 10,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0149',
    heroClass: 'Rogue',
    branch: 'Mastery Branch 1',
    tier: 3,
    name: 'Ascension Talent Node 1-149',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 11,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  },
  {
    id: 'tal_ds_p1_0150',
    heroClass: 'Warrior',
    branch: 'Mastery Branch 1',
    tier: 4,
    name: 'Ascension Talent Node 1-150',
    icon: '✨',
    maxRank: 5,
    bonusAttr: 'PhysicalAttackPower',
    bonusVal: 2,
    isPercent: true,
    summary: 'Permanently increases primary combat attributes.'
  }
];
